import type { MotionTemplate } from './video';

const noPartner='Only the referenced character appears. The viewer is implied by the lens; no viewer hand, extra face or additional character enters.';
const identityMotion='Preserve the approved face, original costume, coverage, body proportions and accessories throughout the exaggerated acting. Drive motion through connected joints, supported upper-body movement and readable facial expressions. Existing hair, ears and clothing follow with a short delay. Any drawn motion smear immediately resolves into the same character. Keep the background and support surfaces stationary. Never animate this as a rigid wobble of the entire image or change body volume to create movement.';

/** Dedicated opening frames for two bold, immediately readable group-chat reactions. */
export const chatReactionTheatreTemplates:MotionTemplate[]=[
  {
    id:'theatre-table-laugh-burst',name:'笑到拍桌，憋住半秒又笑崩',category:'放肆大笑',emoji:'✦',caption:'哈哈哈哈哈哈',
    hook:'仰头笑到连拍三下桌，刚想正经看你半秒，又一次笑弯腰，彻底收不住。',
    scene:'The character sits on a stable seat behind an ordinary real dark-laminate home computer desk. The tabletop naturally hides the waist and lower body. The image-right {{grip}} rests flat near the front desk edge; the other grip covers only the lower edge of the mouth in an unsuccessful attempt to suppress laughter. A monitor corner, a simple tissue packet and a mousepad sit far back, clear of both grips and the character movement. The room has modest household lighting and a casually used desk surface. Keep the desktop, monitor and all background objects completely stationary.',
    pose:'Face the viewer in a frontal medium-close view with the complete head and both {{grip}}s visible. Raise the shoulders in barely contained amusement, eyes already narrowing into delighted crescents and the mouth corners visibly trying to grin around the lightly covering grip. The face occupies approximately 35 percent of image height, with clear headroom above the hairstyle for a large supported backward upper-body recoil. Keep the spine supported by the seat and the desk edge clear.',
    beats:[
      'Lose the attempt to hold it in: immediately pull the covering {{grip}} clear of the mouth and recoil the shoulders and upper body backward in one large delighted release while remaining seated. Lift the chin only enough to accent the release; keep the face mostly toward the lens so both laughing eyes and the whole mouth remain visible, never facing the ceiling. Open the mouth into a huge drawn laughing shape and squeeze the eyes into distinct happy crescents. Move the released grip to the own belly over the unchanged clothes, keeping the motion partly concealed by the desk. The other grip remains poised over its original desk position.',
      'Perform exactly three fast, strong coordinated laughter pulses through the shoulders, upper torso and forward-readable head. On each pulse the image-right {{grip}} lifts decisively, slaps the same clear spot on the desktop once with visible contact, then snaps back before the next slap. Let the open laughing mouth and crescent eyes visibly compress and stretch with these large cartoon pulses, then recover recognizable features. The belly-holding grip follows the contracting torso instead of floating separately. Two large clear cartoon tear droplets flick from the outer eye corners during the burst; no tear fountain forms. Keep the whole face readable. The desk, monitor and camera do not shake.',
      'Abruptly stop the pulses and bring the head upright, looking directly at the viewer as if trying to regain dignity. Close the mouth into a strained straight line, widen the eyes briefly and hold still for only a short half-beat. Both shoulders remain tense and the mouth corners begin to betray another grin. Do not spend this beat wiping tears or adding a new prop.',
      'Fail immediately and break into a second huge open-mouth laughing expression. Fold the upper body forward over the desk, visibly placing both {{grip}}s on the near desk edge for support, then give exactly two more coordinated shoulder-and-torso laughter pulses. Keep the chin lifted enough that the whole laughing face stays visible above the tabletop instead of landing in it. End still bent forward, eyes tightly smiling, shamelessly delighted and unable to recover.',
    ],
    sound:'One clothing swish at the backward shoulder-and-body release, exactly three firm palm-or-paw tabletop slaps with clear separation, a brief quiet pause, then two short sleeve and seated-body rustles during the renewed laughing pulses. No laughter audio, breathy vocalization, speech or music; the laughter is conveyed entirely by visible acting.',
    check:'第一波仰头大笑配三次明确拍桌，憋住半秒后第二波前折再笑两拍；脸始终露在桌面上方。桌子与背景不摇，身形和服饰不随笑声膨胀。',loop:false,
    theatre:{edition:2,motive:'看到太好笑的东西就完全不顾形象，越想认真越收不住。',trigger:'和观众对上眼，本来想憋住的笑一下子决堤。',payoff:'以为终于能正经半秒，下一次笑反而把整个人都笑弯了。',labels:['捂嘴失败仰头笑','笑三拍连拍三下桌','憋住半秒看着你','又笑崩撑桌弯腰'],ends:[.1,.48,.6,1],camera:'Use one fixed frontal camera at the seated character face height. Frame the complete supported backward body recoil and the later supported forward fold without reframing. Preserve the table line and background positions exactly; no camera shake, cut or zoom.',secondaryActor:noPartner,actionStyle:`${identityMotion} Make the two laughter bursts unmistakably large and rhythmically distinct: the first rocks the shoulders and upper body back with three desk contacts while keeping the face toward the lens, the second folds forward with two shoulder pulses. A tiny held attempt at composure separates them. Use genuine joint movement and elastic facial drawing rather than gentle bobbing.`,framing:'Square frontal medium-close seated composition. The face begins about 35 percent of image height, both grips and the near dark-laminate desk edge are visible, and the waist is hidden. Keep visible clear space above the hairstyle for the supported backward body recoil. Leave room above the desk for the later forward-folded face to remain completely readable. Keep monitor corner, tissue packet and mousepad behind and outside both hand paths.',gif:[0,1]},
  },
  {
    id:'theatre-nosy-closeup',name:'发生什么了？脸都凑到你屏幕上',category:'贴脸吃瓜',emoji:'◉',caption:'让我看看',
    hook:'一听有事立刻把脸凑满屏，左看看右看看，最后还贴着屏幕等你接着说。',
    scene:'The character sits on a stable seat behind a low ordinary wooden living-room coffee table. Both {{grip}}s rest on the tabletop with relaxed elbows, and the lower body is concealed by the table. A plain beige sofa with a folded household blanket is in the background; a TV remote and an empty cup remain far back, clear of the movement path. Use an everyday lived-in room and a continuous stable tabletop in front of the character. Leave enough distance between the seated character and lens for a substantial supported forward lean. The camera starts at face height and stays there.',
    pose:'Face the viewer straight on, eyes open in curiosity with one eyebrow slightly raised and the mouth forming a small questioning circle. Lean forward only a little, keeping both {{grip}}s visibly supported on the table and the shoulders connected naturally to the seated body. The face begins around 30–35 percent of image height in a moderately wide portrait composition; this is the anticipation before the extreme close-up, not the close-up itself.',
    beats:[
      'Notice an implied bit of commotion: dart the eyes briefly toward one side of the lens, snap them back to the viewer and lift both eyebrows in sudden curiosity. The head follows with one small alert turn while both grips remain on the tabletop. No additional person or event appears in the room.',
      'Plant both {{grip}}s firmly and slide them forward along the real tabletop while committing the connected shoulders and upper body into a quick forward lean toward the lens. The seated support remains stable. Bring the face from roughly one third of the frame height to about 85–90 percent, so it comically fills almost the entire screen. Crop only the outer hair if needed; keep both eyes, the nose and the whole mouth inside the frame. Stop short of the lens without contact. This enlargement comes entirely from the character approaching, never a camera zoom or an isolated floating head.',
      'Stay extremely close and inspect the viewer by moving the actual head a short distance left, then right, with small changes of angle. The eyes track each inspected side together with the head; both shoulders follow naturally below the close crop. Add one small nose twitch or one curious blink between the two looks. Keep the facial features and recognizable proportions stable without fisheye distortion, stretching the face or moving separate facial parts independently. Do not back away during this extended curious inspection.',
      'Lean back only a few centimeters, leaving the complete face still around 70 percent of image height and conspicuously close to the viewer. Raise one eyebrow in dawning amused understanding and let the questioning mouth become a tiny knowing grin. Hold that eager curious face as if waiting for the next detail. Keep the hands supported on the tabletop below the crop; do not reset to the distant opening position or add a pointing, poking or kissing gesture.',
    ],
    sound:'One brief sleeve rustle at the alert reaction, a soft two-grip slide across the tabletop during the fast approach and faint clothing movement during the left-right inspection. Quiet living-room ambience; no lens impact, speech, vocalization or music.',
    check:'必须由双手沿桌滑动、肩膀带着身体前倾，把脸从三分之一画幅送到接近满屏。顶点只拍脸，两眼鼻嘴都完整；最后仍很近，不缩回远处或变成戳镜头。',loop:false,
    theatre:{edition:2,motive:'只要群里有点热闹，就想第一个挤到前面把细节看清楚。',trigger:'好像听到了什么不得了的事，眼睛和眉毛立刻警觉起来。',payoff:'脸已经把屏幕占满，还要左右端详，退了几厘米也舍不得离开。',labels:['有动静立刻警觉','整张脸迅速凑满屏','贴着屏幕左右看','还挨得很近等下文'],ends:[.1,.25,23/30,1],camera:'Hold one fixed face-height frontal camera with a natural portrait perspective. The character approaches the lens through an actual supported body lean; do not zoom, dolly, reframe downward or use a fisheye lens. At the closest point the frame contains the face, with both eyes, nose and mouth intact. Preserve the still background until the approaching face naturally occludes it.',secondaryActor:noPartner,actionStyle:`${identityMotion} Use one decisive forward approach followed by a sustained enormous curious face. The comedic event is the character crossing the normal conversational distance and continuing to inspect the viewer at that distance. Keep the head attached to its following shoulders and the hands sliding on the same table; no lens licking, kiss, impact or emergence through the screen.`,framing:'Square straight-on moderately wide opening portrait with the face about 30–35 percent of image height, both hands resting on the low wooden coffee table and the lower body hidden. Place the lens at face height and preserve clear tabletop in the foreground for the hands to slide forward. The opening includes the complete head and shoulder support; the intended approach will fill 85–90 percent of frame height with the face alone, keeping both eyes, nose and whole mouth inside and cropping only outer hair. The sofa, folded blanket, remote and empty cup remain behind the movement path.',gif:[0,1]},
  },
];
