import type { MotionTemplate } from './video';

const motion='Use bold pose-to-pose cartoon acting: a brief readable setup, a fast committed action and a contrasting comic payoff. Limbs move the props through visible contact; the body actually travels when specified. Let existing hair, ears and clothing follow with a delayed bounce, then settle. Brief drawn smears may accent fast motion but immediately recover the approved silhouette. Keep the face legible at sticker size, the ordinary room stable and the original outfit unchanged. No idle swaying, unmotivated prop motion or continuous camera shake.';
const noPartner='Only the referenced main character is visible. The viewer is implied by eye contact with the lens; no viewer hand or second character enters.';

/** Six separate opening compositions; each needs its own first-frame image. */
export const comedyTheatreTemplates:MotionTemplate[]=[
  {
    id:'theatre-keyboard-mercy',name:'键盘举起来了，舍不得又哄回去',category:'破防嘴硬',emoji:'⌨',caption:'算了，键盘没错',
    hook:'举过头顶都准备砸了，看一眼键盘又舍不得，抱回来擦擦哄哄，最后瞪你。',
    scene:'A miniature character stands firmly on an ordinary slightly worn computer desk. The character holds one compact cordless black keyboard horizontally across the upper torso with both {{grip}}s around its short ends. The keyboard is small and light enough to lift overhead. A stationary monitor lower bezel and a separate mouse are behind the character, away from the action. The space above the head and in front of the feet is clear. Use modest household lighting, a used desk surface and photographic everyday computer equipment rather than a showroom.',
    pose:'Plant both feet apart, bend the knees slightly and glare angrily at the viewer with lowered brows. Hold the same keyboard securely against the upper torso, keeping the face completely visible above it. Both {{arm}}s are bent in a loaded preparation to lift. Preserve the original costume, proportions and accessories.',
    beats:[
      'Grip the two ends of the keyboard firmly, bend the knees in one quick wind-up and straighten the whole body while raising both {{arm}}s high overhead. The keyboard follows the connected grips into a dramatic mock smashing pose. Keep both feet planted and the keyboard intact; this is the threat before a strike, not a strike.',
      'Just before any downward swing, look up at the keyboard and stop abruptly. The angry mouth collapses into a worried little pout, elbows soften and the shoulders lose their fierce tension. Hold this sudden change long enough to read, with the keyboard still securely supported by both grips.',
      'Lower the same keyboard carefully against the chest. Support its lower edge with one {{arm}} while the other {{grip}} gives the top surface two quick gentle wiping strokes and one affectionate pat. Hunch protectively around it, changing from explosive anger to exaggerated tenderness. Every key remains attached; nothing is struck or broken.',
      'Hug the keyboard close with both {{arm}}s, straighten just a little and slowly turn the eyes back to the viewer. Hold a sharp accusing side-eye and one offended chin lift as if the keyboard was innocent all along. Finish cradling the intact keyboard; do not raise it for another attack.',
    ],
    sound:'A quick clothing swish during the overhead lift, a short handling creak from the intact keyboard casing, two soft wiping sounds and one gentle pat, then quiet computer-room tone. No impact, breaking keys, speech, vocalization or music.',
    check:'先举过头顶，再看键盘急停；两次擦拭后轻拍一下。键盘始终同一块且不落地，结尾是抱着键盘瞪观众。',loop:false,
    theatre:{edition:2,motive:'气到想摔东西，真正举起来却心疼自己的键盘。',trigger:'看着观众越想越气，双手已经握紧键盘。',payoff:'舍不得砸，反而把键盘当宝贝哄，最后把锅甩给观众。',labels:['举过头顶要砸','看键盘突然怂','抱回来擦擦哄','护着键盘瞪你'],ends:[.27,.42,.77,1],camera:'Use one locked frontal camera at character eye height. Show the grounded wind-up, full overhead keyboard and subsequent protective hug together. No cut, zoom or simulated camera impact.',secondaryActor:noPartner,actionStyle:motion,framing:'Square full-body view with both planted feet and the complete keyboard visible. The character occupies about 55 percent of the image height in the lower part of the composition; reserve the upper 35–40 percent as clean wall and unobstructed air for the complete overhead keyboard lift. Keep the monitor bezel far to one side, outside that lifting corridor, with the face clear above the keyboard.',gif:[0,1]},
  },
  {
    id:'theatre-phone-fake-sleep',name:'说睡了，手还偷偷摸手机',category:'摸鱼露馅',emoji:'☾',caption:'睡了，真睡了',
    hook:'发现你在看，立刻扣下手机把脸埋进枕头；眼睛还闭着，手已经偷偷伸回去了。',
    scene:'An ordinary bed has washed pale-blue tiny-floral cotton sheets and one large pale cream-yellow pillow. The fully dressed small character lies belly-down behind the pillow, which naturally hides the front of the torso and lower body. Both elbows press into the pillow top, and both {{grip}}s hold one phone upright. The screen faces the character and the phone back faces the camera. Existing hair or appendages rest to the sides of the pillow. Leave a visible clear patch of sheet beside the pillow for the phone to be placed. Show normal fabric wrinkles and gentle household light.',
    pose:'Look down at the upright phone with a sly private smile. Keep the complete face above the pillow, both elbows visibly supported and both grips attached to the phone. The original outfit remains fully worn; the pillow and framing cover the body naturally. No back reveal or lower-body posing.',
    beats:[
      'Make two quick small scrolling taps with one {{grip}} while the other steadies the upright phone. The eyes follow the screen and the grin widens briefly. Keep the elbows planted on the pillow and the phone screen facing the character.',
      'Suddenly notice the viewer and snap the eyes toward the lens. With a guilty wide-eyed start, rotate the same phone screen-down, lower it to the clear sheet beside the pillow and slide it a short distance along the fabric with visible grip contact. Release it only after it lies flat. The phone remains plainly visible beside the pillow, never hidden underneath.',
      'Immediately drop the entire face forward into the soft pillow in an exaggerated pretend-sleep flop, with eyes closed before contact. The pillow compresses under the cheek and forehead; the body remains supported on the bed. Keep one {{arm}} bent as a stable support while the other settles near the pillow edge. Existing hair bounces once and falls around the pillow.',
      'Keep the eyes closed and the cheek pressed into the pillow as if deeply asleep. Without lifting the head, creep the free {{grip}} sideways across the sheet until its tips touch the visible phone. Freeze for a guilty half-beat with the phone still lying flat and the other arm supporting the pose. That sneaking reach, not a reopened eye or a second phone, reveals the lie.',
    ],
    sound:'Two faint phone taps, a short fabric slide as the phone is laid screen-down, one muffled soft pillow flop and a tiny sheet rustle during the sneaking reach. No snoring, speech, vocalization or music.',
    check:'手机先翻成屏朝下放稳，再扎枕头；手机始终在枕旁可见。最后闭眼伸手摸手机，另一只手仍有支撑，不掀衣服或翻腿。',loop:false,
    theatre:{edition:2,motive:'明明说睡了，却还想再刷一眼手机。',trigger:'正偷笑刷手机，突然发现观众一直在看。',payoff:'脸已经埋进枕头装睡，手却诚实地去够手机。',labels:['偷偷刷两下','被抓赶紧扣手机','脸扎枕头装睡','闭着眼还要摸'],ends:[.18,.44,.68,1],camera:'Keep one steady slightly elevated three-quarter bedside view, close to head height. Follow no movement with the camera. The face, supported elbows, pillow and phone resting beside it remain inside the same composition.',secondaryActor:noPartner,actionStyle:motion,framing:'Square close-medium bedside composition. The large pale-yellow pillow naturally conceals the torso; frame the expressive face, both elbows and the single upright phone above it. Include a clear side strip of sheet within arm reach for the later screen-down phone. Keep the head, final cheek contact and sneaking grip visible without showing the lower body.',gif:[0,1]},
  },
  {
    id:'theatre-soda-backfire',name:'汽水喷了自己，还要怪你',category:'翻车甩锅',emoji:'◌',caption:'都怪你！',
    hook:'得意地开汽水，泡沫先糊了自己的脸；顶着一撮白胡子，还要指着你生气。',
    scene:'The small character sits behind an ordinary household dining table covered by a pale mint plastic tablecloth. The tabletop naturally conceals the lower torso and body, leaving the large expressive face, sleeves and both grips visible. One transparent bottle of orange soda rests upright on the tabletop close to the character, with its white plastic screw cap still attached. The bottle top is below the chin and offset to image left, leaving a clear gap between the opening and the face. One {{grip}} steadies the bottle body on the table while the other grips its cap. A real orange and a simple tissue packet sit farther back, outside the action area. Keep the bottle size manageable and the surroundings modest and lived-in.',
    pose:'Sit securely behind the table, holding the bottle steady on the tabletop and gripping the attached cap with the other {{grip}}. Turn the face toward the viewer with a smug sideways grin and raised chin, as if opening this bottle will be effortless. Leave the eyes and mouth fully visible; the bottle never covers the face. Keep the original outfit unchanged behind the natural tabletop occlusion.',
    beats:[
      'Give the viewer one proud side-eye and tighten the grip around the still-attached white cap. Shift the shoulders forward in a small confident preparation while the other {{grip}} keeps the bottle base firmly on the tabletop.',
      'Twist the same cap loose and lift it visibly clear of the opening, keeping it in that grip. Immediately a single brief burst of white soda foam spurts upward and a few soft flecks land on the character own face. Recoil the head and shoulders with wide eyes, while the steadying grip keeps the bottle upright on the table. The cap stays held and never flies away.',
      'The short foam burst stops at once. Freeze in shocked disbelief as the foam settles, leaving just a small comic white foam moustache above the mouth. Both eyes stay clean and readable. Blink once and turn the stare slowly toward the viewer; no continuous fountain or spreading table flood follows.',
      'Place the held cap on the tabletop beside the bottle and release it after contact. Using that now-free {{grip}}, point accusingly at the viewer while puffing the cheeks beneath the silly foam moustache. Keep the other grip resting on the same upright bottle. End with indignant eye contact, visibly blaming the wrong person.',
    ],
    sound:'A short plastic cap twist and release hiss, one brief fizzy foam sputter, a tiny cap tap when set on the table and quiet dining-room tone. No prolonged spray, speech, vocalization or music.',
    check:'瓶盖先旋松提起才喷；喷沫短促，眼睛保持清楚。瓶始终放桌上；最后先放下盖子，才能用空手指观众。',loop:false,
    theatre:{edition:2,motive:'想在观众面前装熟练，翻车后又舍不得认错。',trigger:'自信拧开那瓶看似乖巧的汽水。',payoff:'脸上还有泡沫小胡子，却一本正经地指着观众甩锅。',labels:['得意看你一眼','拧盖泡沫扑脸','顶着白胡子呆住','放下盖子怪你'],ends:[.13,.45,.69,1],camera:'Lock a three-quarter frontal camera at the character eye level. Keep both contact grips, the bottle mouth, full face and cap landing area visible in the same shot. Do not zoom into the foam or shake the frame.',secondaryActor:noPartner,actionStyle:motion,framing:'Square seated medium-close composition behind the dining table, which naturally hides the lower torso and body. Show the large face, original cardigan sleeves, both contact grips and the complete bottle standing on the tabletop below chin height. Position the bottle mouth a little to image left of the face with visible space between them. Keep room beside the bottle for the cap and in front of the free arm for the final pointing gesture. The orange and tissue packet stay small in the background.',gif:[0,1]},
  },
  {
    id:'theatre-box-escape',name:'社恐缩进纸箱，连箱一起溜',category:'社恐撤退',emoji:'▱',caption:'你没看见我',
    hook:'被盯住先缩进箱子，以为藏得很好，结果整个纸箱开始偷偷往外溜。',
    scene:'On ordinary living-room ceramic floor tiles, a small real corrugated delivery box sits open with all four top flaps folded outward. The small character crouches inside; the front panel hides the torso, leaving only the face, existing hair or appendages and two {{grip}}s holding the front rim visible. The box has an open underside, allowing the hidden feet to contact the floor; this underside need not be visible from the camera. A plain shoe rack and everyday slippers sit far behind. Keep the visible floor strip to image right clear as a continuous escape route out of frame. No packaging text or brand is required.',
    pose:'Peek above the front box rim with a flat wide-eyed or half-lidded stare aimed directly at the viewer. Both {{grip}}s rest visibly on the rim, shoulders lowered inside the box. Keep the character balanced on its hidden feet and the cardboard base edges resting on the tiles. Existing hair or soft appendages fit naturally beside the face, ready to tuck inside.',
    beats:[
      'Freeze at the viewer stare for one uncomfortable short beat. The eyes open a little wider, both grips tighten on the rim and the head lowers slightly in an obvious decision to hide. The box remains stationary and grounded.',
      'Crouch down fully below the rim, drawing both {{grip}}s inside. Soft hair or existing flexible appendages follow the head down into the same box instead of remaining floating above it. The four flaps stay folded outward and the box remains open, with no visible character above the rim.',
      'From inside, use the hidden feet through the open underside to push against the tiled floor. The grounded box makes two short guilty shuffles, first a little left and then right, each starting with a small cardboard flex from internal contact. The box does not lift, spin, transform or slide without a physical push.',
      'Commit to a brisk rightward escape with several quick hidden foot pushes, sliding the same grounded box along the clear tiled path. Move most of the box out through image right, leaving only its trailing corner visible. Pause there and cautiously lift one eye above that trailing corner for a final guilty peek toward the viewer. Keep the head mostly hidden and the box shape intact.',
    ],
    sound:'A small cardboard rim creak, a brief clothing rustle as the character ducks inside, two short cardboard scrapes and a quick soft series of floor scuffs during the grounded escape. No speech, vocalization or music.',
    check:'先连同头发收进箱，再由隐藏的脚蹬地挪箱。四盖片始终外翻，箱底贴地；最后大半箱出右边，只冒一只眼。',loop:false,
    theatre:{edition:2,motive:'只要看不见我，就可以假装自己没参与这场聊天。',trigger:'从纸箱里探头时，恰好跟观众对上视线。',payoff:'人是藏好了，纸箱却当着观众的面一路逃跑，还心虚偷看。',labels:['被盯住先僵住','整只缩回纸箱','箱子心虚挪两下','连箱溜走偷看'],ends:[.14,.36,.56,1],camera:'Keep one locked low camera facing the tiled floor and box at the peeking character eye height. The escape is actual box translation across the room, not panning or moving the whole image. Preserve the stationary tile grid and distant shoe rack.',secondaryActor:noPartner,actionStyle:motion,framing:'Square low frontal medium shot. Place the open box and large readable peeking face toward image left, with both grips on the front rim. Keep a clear strip of tiled floor to the right leading continuously out of shot. Include enough box height to read its grounded contact while keeping its underside hidden. No overhead view.',gif:[0,1]},
  },
  {
    id:'theatre-takeout-return',name:'告辞跑了，又回来拿外卖',category:'跑路露馅',emoji:'➜',caption:'走了，饭得带上',
    hook:'挥挥手跑得很潇洒，半秒后又心虚折回来拿外卖，连走都舍不得转身。',
    scene:'An ordinary rented-room floor runs beside a low doorway threshold. The small character stands near the center, angled toward a clear exit route at image right. A small light-brown paper takeout bag with two visible loop handles sits on the floor at the character front-left; the bag reaches only knee height and is light enough to carry. Normal shoes by the doorway, a plain wall and lightly worn flooring establish an everyday home. Keep the bag, character and rightward route on the same continuous floor plane with no step blocking the path.',
    pose:'Raise one {{grip}} in preparation for a smug goodbye wave, with the other empty at the side. Begin a forward step toward image right while looking back at the viewer with a confident little grin. Keep both feet, the grounded takeout bag and its handles clearly visible. The bag is not already held or attached to the character.',
    beats:[
      'Give the viewer one brisk dismissive goodbye wave with the raised {{grip}}, lift the chin proudly and turn the shoulders toward the clear route at image right. The takeout bag stays on the floor at the front-left.',
      'Take three quick committed running steps and exit completely through image right, with hair and clothing trailing the actual movement. Leave the same takeout bag behind in its original place. Hold the abandoned bag and empty route alone for one brief comic half-beat; do not cut or move the camera.',
      'Rush back in from image right, brake beside the forgotten bag with a visible planted foot and a guilty sideways glance. Bend toward it and close one {{grip}} securely around the same two loop handles before lifting. The paper bag rises only after physical grip contact; it never jumps or floats into the hand.',
      'Keep the recovered bag held by its handles, take two quick backward steps toward image right and escape again while facing the viewer with an embarrassed trying-to-look-casual expression. The same bag travels with the gripping arm and stays clear of the floor. Give one last furtive glance just before disappearing; end with only a very short empty-floor hold.',
    ],
    sound:'Three quick light footfalls, a short quiet empty-room beat, rapid returning footfalls with a gentle shoe scuff at the brake, paper-handle crinkles and two receding steps. No speech, vocalization or music.',
    check:'第一次确实跑出画面，纸袋原地留下；回来先刹住并抓住提手再提袋，不能自动飞到手上。倒退跑路的路面与首帧一致。',loop:false,
    theatre:{edition:2,motive:'想潇洒退出，但最惦记的外卖不能落下。',trigger:'对着观众摆出“我先走了”的得意架势。',payoff:'人跑了，饭还在；只好当着观众的面折回来，心虚倒退溜走。',labels:['得意挥手告辞','跑掉却忘了饭','折返急刹抓袋','看着你倒退溜'],ends:[.12,.4,.73,1],camera:'Use a fixed low frontal view of the full floor route. The character exits and reenters through the same right edge. Keep the forgotten bag visible during the brief empty-frame beat; no tracking, zoom or cut.',secondaryActor:noPartner,actionStyle:motion,framing:'Square medium-full view at small-character eye height. Include the entire body and both feet near the center, the knee-high paper bag at front-left and clear floor to image right for entry and exit. Keep the low threshold behind the route rather than across it. Ordinary shoes and wall details remain peripheral; preserve the bag handles for a readable return grip.',gif:[0,1]},
  },
  {
    id:'theatre-coffee-collapse',name:'咖啡续命失败，脸先下班了',category:'强撑下线',emoji:'☕',caption:'我还能……',
    hook:'信心满满喝口咖啡，杯子刚放稳就栽进枕头，手还举着赞硬撑，最后连拇指也倒了。',
    scene:'The small fully dressed character sits on a suitably sized seat behind an ordinary computer desk, with the desktop naturally hiding the waist and lower body. One white coffee cup is held by its handle in the image-left {{grip}} near the mouth; it contains coffee at the level shown in the first frame and emits no steam. The other {{grip}} supports the body on the desk. A soft square mouse-gray pillow lies flat directly in front of the character, separate from the cup. A black keyboard stays farther back, and an everyday water cup and charging cable remain near the desk edges. Leave a stable cup landing area to image left, away from the pillow.',
    pose:'Sit upright with a half-lidded, exhausted but overconfident grin, proudly holding the single white cup close to the mouth. Keep the second {{grip}} visibly braced on the desk, the pillow flat and ready to receive the head, and the full face large in frame. Maintain the approved outfit and seated support; the cup and pillow must not overlap.',
    beats:[
      'Lift the white cup just enough to take one confident sip, keeping its rim aligned with the mouth, then lower it clear of the face. Briefly straighten and give the viewer an overly determined look as if fully recharged. The remaining coffee stays inside the same cup without spilling.',
      'Move the cup to the clear landing area beside the character, well away from the gray pillow, place its base flat on the desk and release the handle only after contact. As the grip withdraws, both eyelids begin to sag and the confident shoulders abruptly lose their tension. The other grip remains a stable support on the desk.',
      'With the cup now safely parked, pitch the head and upper body forward in one sudden sleepy flop, landing the face squarely into the soft gray pillow. The pillow visibly compresses and cushions the head. Keep the body supported by the seat and desk, the clothes unchanged and the parked cup upright and untouched.',
      'Keep the face buried in the pillow and raise the former cup-holding {{grip}} beside the head into a stubborn thumbs-up. For a paw, simple limb or rigid gripper, use its existing compatible positive gesture rather than adding human fingers. Hold that last claim of competence briefly, then let the raised gesture slowly droop and rest on the desk. The other arm and pillow continue supporting the collapsed pose.',
    ],
    sound:'A tiny cup handling sound and a gentle ceramic tap as it is parked, one soft pillow thump and a final sleeve rustle as the raised limb gives up. Quiet computer-room ambience; no spilling, snoring, speech, vocalization or music.',
    check:'先喝一口，再把杯子放到枕头旁的安全位置并松手；随后脸才栽下。杯子不翻，最后竖赞的手慢慢耷拉，不举杯睡觉。',loop:false,
    theatre:{edition:2,motive:'嘴上坚持自己还能干，身体已经提前下班。',trigger:'把一口咖啡当成马上就能满血复活的保证。',payoff:'脸都埋进枕头了，还要竖个赞硬撑，最后连那只手也撑不住。',labels:['喝口咖啡装精神','杯子放稳眼皮垮','脸先栽进软枕','竖赞硬撑又耷拉'],ends:[.22,.46,.65,1],camera:'Hold one fixed frontal three-quarter close-medium desk view, slightly above tabletop level. Keep the full face, cup landing area, pillow and final raised grip in view together. No camera bob, cut or zoom.',secondaryActor:noPartner,actionStyle:motion,framing:'Square close-medium seated composition with the waist naturally hidden behind the desk. Keep the large face and both grips readable above it. The flat gray pillow occupies the near-center tabletop; reserve a separate visible area to one side for the white cup. Leave enough headroom to read the upright sip and enough side room for the final positive gesture beside the collapsed head.',gif:[0,1]},
  },
];
