import type { ReactionReference } from './reaction-research';

export const comedyReferences: ReactionReference[] = [
  {
    id: 'comedy-capoo-keyboard', family: 'Bugcat Capoo / 咖波',
    title: 'Angry Work · 电脑前破防',
    url: 'https://giphy.com/stickers/angry-capoo-bugcat-Z3Op6V4KdP7ZQWft5O',
    format: 'GIF 动态贴图', verification: '浏览器已看多个相位',
    provenance: 'GIPHY 认证 Capoo，Source 链向官方 YouTube',
    theme: '日常翻车', uses: ['破防', '游戏输了', '这活干不了'],
    observed: '电脑摊开在前，咖波皱眉并摆开双臂；另一相位头部倒到电脑后方，额头上方有白色冲击线和灰色小方块；频道缩略图还显示电脑被掀起。',
    mechanism: '情绪通过身体与道具的接触产生可读的后果，普通电脑也能成为笑点。',
    adaptation: '本轮原创「键盘举起来了，舍不得又哄回去」：怒举键盘要砸→突然心疼→飞快抱回来擦两下→抬眼假装没事。',
    firstFrame: '普通电脑桌、旧鼠标垫、水杯和充电线；双手已经抓住小键盘两侧，上方留出举起空间，使用本条独立首帧。',
    popularity: '2026-09-25 浏览器详情页为 16,510,929 GIPHY Views。',
    boundary: '没有逐帧复原原作次序或次数；心疼键盘的反转为原创。Views 是累计服务展示，不是独立人数、近期增速或 QQ 转发量。',
  },
  {
    id: 'comedy-phoebe-secret-phone', family: '菲比',
    title: '偷玩手机菲比 · 证据还在',
    url: 'https://kato-shoko705.github.io/Phoebe-Hub/images/偷玩手机菲比.gif',
    format: 'GIF 动图', verification: '浏览器截图核验两种状态',
    provenance: 'Phoebe-Hub 粉丝收集站，原动画作者未核实',
    theme: '抓包装乖', uses: ['说睡了却在线', '摸鱼被抓', '我不在'],
    observed: '菲比趴在摄影床铺和枕头上，双手拿手机，紫色屏光映脸；另一相位手机放在床上，她抬头看观众、作无辜表情。',
    mechanism: '观众先看见证据，角色再装无辜；手机的移动比单纯换表情更能交代事件。',
    adaptation: '本轮原创「说睡了，手还偷偷摸手机」：刷手机偷笑→被发现后把手机翻扣在枕旁→脸埋枕头闭眼装睡→手却偷偷伸回手机。',
    firstFrame: '普通床铺、淡蓝碎花床单、浅黄色大枕头；双肘压枕、双手握手机、屏幕朝自己，枕旁留放手机和伸手空间，脸与手清楚。',
    popularity: '收集站列为动态图，收录日期 2026-06-25；没有该条公开浏览、下载或 QQ 转发数。',
    boundary: '截图支持玩手机与抬头装无辜，未逐帧计时；闭眼摸手机的收尾为原创，站内“超可爱”标签不代表传播量。',
  },
  {
    id: 'comedy-phoebe-soda-backfire', family: '菲比',
    title: '怎么老被炸呀 · 意外后的狼狈结果',
    url: 'https://kato-shoko705.github.io/Phoebe-Hub/images/怎么老被炸呀.gif',
    format: 'GIF 动图', verification: '浏览器已看两个明显相位',
    provenance: 'Phoebe-Hub 粉丝收集站，原动画作者未核实',
    theme: '日常翻车', uses: ['又翻车', '又中招', '都怪你'],
    observed: '摄影环境中，亮色火团在后方爆开，小人浮在空中睁眼；另一相位出现黑烟，角色落地、闭眼并露出痛苦表情。',
    mechanism: '可爱角色遇到过量外界反应，事后留下清楚的狼狈状态，反差有因有果。',
    adaptation: '本轮原创「汽水喷了自己，还要怪你」：旋开瓶盖→短促泡沫扑脸→上唇留泡沫胡子→把盖子放桌上，用空手指向观众甩锅。',
    firstFrame: '普通饭桌和浅绿塑料桌布，角色坐桌后；一手稳住桌上小汽水瓶，一手握仍闭合的瓶盖，坏笑看观众，瓶口在脸侧下方。',
    popularity: '站内收录日期 2026-07-02；未见单条公开传播统计。',
    boundary: '原作是夸张爆炸反应；生活化汽水事故、泡沫胡子和甩锅均为本项目原创，未声称原图包含开瓶动作。',
  },
  {
    id: 'comedy-pusheen-box-peek', family: 'Pusheen',
    title: 'Cat No · 纸箱里只露半张脸',
    url: 'https://giphy.com/stickers/pusheen-pip-pipthekitten-ef4WzI4OGp5qG5qwcy',
    format: 'GIF 动态贴图', verification: '详情页与官方搜索画面已查看',
    provenance: 'GIPHY 认证 Pusheen，Source 为 pusheen.com',
    theme: '躲藏撤退', uses: ['潜水', '偷偷看', '社恐', '我不在'],
    observed: '褐色小猫藏在开口牛皮纸箱后，箱沿上只露眼睛、耳朵和头顶；箱体有皱线，四块箱盖可读。',
    mechanism: '大箱子与半张小脸形成清楚的遮挡关系，把“在线但不出现”变成易读的画面。',
    adaptation: '本轮原创「社恐缩进纸箱，连箱一起溜」：箱沿偷看→发现观众后嗖地蹲下→脚推着箱底向右滑走→在画面边缘重新露眼偷看。箱盖保持打开。',
    firstFrame: '普通玄关地砖、鞋柜底和拖鞋；无品牌或收件信息的开口纸箱遮住身体，脸和抓着箱沿的双手可见，四盖外翻，右侧留连续移动空间。',
    popularity: '2026-09-25 浏览器详情页为 27,642,548 GIPHY Views。',
    boundary: '仅确认纸箱探头构图，未确认原作完整躲藏或咬箱周期；移箱逃跑是原创。Views 不等于 QQ 热度或主动转发。',
  },
  {
    id: 'comedy-capoo-takeout-return', family: 'Bugcat Capoo / 咖波',
    title: '职场大爆走 · 叼吐司赶路',
    url: 'https://store.line.me/stickershop/product/17228844/zh-Hant',
    format: '动态贴图（APNG）', verification: '官方预览已看多个动作相位',
    provenance: '亚拉的 LINE 官方套装，具体预览 sticker id 445401383',
    theme: '躲藏撤退', uses: ['告辞', '我先溜了', '马上来', '要迟到了'],
    observed: '咖波叼吐司、提公文包、压低身体前冲；截图中有跑出预览区域后的留白，也有横向压扁、速度线和挥动小脚的跑步相位。',
    mechanism: '起跑姿态、真实位移、离开后的留白共同交代“走了”，随身道具又解释为什么走。',
    adaptation: '本轮原创「告辞跑了，又回来拿外卖」：摆手告辞→从右侧跑出→留空时外卖还在→偷偷回来抓袋子→抱走外卖再次溜走。',
    firstFrame: '普通租房走廊地板，角色回头挥手、小纸袋还在左侧地上；袋子仅膝盖高且双提手可抓，右侧预留连续离场路径。',
    popularity: '2026-09-25 官方套装页心形心愿数为 13.9k；不是具体单条数据。',
    boundary: '原预览表达赶路，不能据此定名“准时下班”。回来拿外卖是原创；套装心愿数不等于销量、动画播放或 QQ 转发。',
  },
  {
    id: 'comedy-capoo-coffee-fail', family: 'Bugcat Capoo / 咖波',
    title: 'Tired Coffee · 喝了也还是困',
    url: 'https://giphy.com/stickers/coffee-capoo-bugcat-r5AqZqd4TZ7KqmFQEx',
    format: 'GIF 动态贴图', verification: '浏览器已看两种明确相位',
    provenance: 'GIPHY 认证 Capoo，Source 链向官方 YouTube',
    theme: '日常翻车', uses: ['累了', '没电', '续命失败', '我还能撑'],
    observed: '系黄领带、垂眼困脸；一相位白杯杯底朝观众、杯沿贴脸，另一相位杯子放低，咖波吐舌垂眼，嘴边有棕色痕迹。',
    mechanism: '道具应该解决问题，表情却说明没有解决；想逞强与真实状态矛盾。',
    adaptation: '本轮原创「咖啡续命失败，脸先下班了」：自信举杯→喝完把杯子放到旁边→眼皮撑不住，脸栽进软枕→手还硬撑着举拇指。',
    firstFrame: '日常电脑桌后，角色一手举白杯、另一手撑桌，灰软枕平放在面前；杯子左侧有独立落点，先放稳再倒头。',
    popularity: '2026-09-25 浏览器详情页为 5,137,207 GIPHY Views。',
    boundary: '原作只核验到举杯与放杯后的困脸，没有看到栽倒；栽软枕和举拇指是原创。Views 是累计服务展示，不是独立用户或 QQ 转发。',
  },
  {
    id: 'comedy-capoo-blanket-backup', family: 'Bugcat Capoo / 咖波',
    title: 'Sleep · 把自己包起来（备选）',
    url: 'https://giphy.com/stickers/sleep-capoo-bugcat-XlZGsZ8jflqn21UhZG',
    format: 'GIF 动态贴图', verification: '浏览器频道与详情页多个相位',
    provenance: 'GIPHY 认证 Capoo，Source 链向官方 YouTube',
    theme: '躲藏撤退', uses: ['自闭', '下线', '不要吵', '装死'],
    observed: '咖波趴在白色软物边缘；另一相位嘴或前肢贴着软物边缘；随后截图中白色软物围成圆圈，只露出蓝色脸。',
    mechanism: '角色主动改变遮挡关系，让退出互动变成整个身体的行为。',
    adaptation: '备选、未作为本轮成图交付：在沙发角瞪人→拉薄毯包住自己→转身背对你→露一眼偷看后又缩回。',
    firstFrame: '普通布沙发、扶手旧薄毯和遥控器；双手握毯边，脸与原本身形仍清楚，为转身留空间。',
    popularity: '2026-09-25 浏览器详情页为 4,643,640 GIPHY Views。',
    boundary: '画面不能严格区分被子与软垫，不称已核验甩被子全过程；原创主动自闭剧情应区别现有掀被子叫起床。Views 不等于 QQ 转发。',
  },
  {
    id: 'comedy-capoo-celebration-backup', family: 'Bugcat Capoo / 咖波',
    title: 'Happy · 高兴到变形（备选）',
    url: 'https://giphy.com/stickers/happy-excited-capoo-K5SrNFyE1BhPZ86tR3',
    format: 'GIF 动态贴图', verification: '详情页夸张相位已查看',
    provenance: 'GIPHY 认证 Capoo，Source 为角色官方 linktr.ee',
    theme: '全身喜剧', uses: ['赢了', '下班', '成功了', '好消息'],
    observed: '蓝色身体被拉成竖直长条，大张嘴，两眼为黄色星形，轮廓旁有抖动线。',
    mechanism: '兴奋改变整个人的形状与重心，眉眼、嘴和身体同步表演。',
    adaptation: '备选、未作为本轮成图交付：兴奋连跳→得意转身却坐进软豆袋→从陷落处举手比耶→咧嘴继续装赢。',
    firstFrame: '普通客厅地垫，旁边放软豆袋或大抱枕；双脚站稳且落点清楚，保留 Margaret 原有身形。',
    popularity: '2026-09-25 浏览器详情页为 59,438,450 GIPHY Views。',
    boundary: '本次只可靠确认夸张拉长相位，未确认跳跃次数或落地；坐进豆袋是原创，不复制咖波的细长体。Views 不等于近期热度。',
  },
  {
    id: 'comedy-pusheen-popcorn-backup', family: 'Pusheen',
    title: 'Food Popcorn · 抱着超大桶（备选）',
    url: 'https://giphy.com/stickers/pusheen-pip-stormy-Ia29rfr4Vqsx2pFSGK',
    format: 'GIF 动态贴图', verification: '浏览器详情页实际画面已查看',
    provenance: 'GIPHY 认证 Pusheen',
    theme: '道具事件', uses: ['吃瓜', '继续说', '看热闹'],
    observed: '浅色角色抱着几乎遮住半张脸的条纹爆米花桶，桶内爆米花有运动线；前景还有另一只小猫的头和尾巴。',
    mechanism: '抱得太满、快挡住视线的道具，使平常小事显得过分认真，可借此组织吃瓜构图。',
    adaptation: '备选、未作为本轮成图交付：淡定吃爆米花看热闹→突然意识到说的是自己→手停嘴边、瞪圆眼→默默把桶挪走装路过。',
    firstFrame: '普通租房客厅、塑料矮凳和旧电视柜；桶在腿上，一手捻一颗爆米花，脸在桶上方无遮挡，手到嘴的路径清楚。',
    popularity: '浏览器详情页为 9,101,586 GIPHY Views；检索缓存旧值 6,658,667，按同一作品记录而非相加。',
    boundary: '只确认大桶与角色的接触和搬运构图，未看到吃到震惊或洒落接回的完整动作；反转是原创。Views 不等于 QQ 转发。',
  },
  {
    id: 'comedy-phoebe-fruit-backup', family: '菲比',
    title: '偷吃水果菲比 · 嘴比手快（备选）',
    url: 'https://kato-shoko705.github.io/Phoebe-Hub/images/偷吃水果菲比.gif',
    format: 'GIF 动图', verification: '浏览器相邻截图核验嘴型与水果位置',
    provenance: 'Phoebe-Hub 粉丝收集站，原动画作者未核实',
    theme: '道具事件', uses: ['饿了', '我全都要', '别抢我的', '身体很诚实'],
    observed: '小人趴在摄影木地板上，背后是普通沙发，面前有苹果、橘子和果盘；夸张大嘴贴近水果，相邻采样中一颗橘子来到嘴前，嘴型改变。',
    mechanism: '小体型与夸张食欲对照，食物参与接触和位置变化，而非只被角色抱着。',
    adaptation: '备选、未作为本轮成图交付：抱胸扭头拒绝→观众递草莓→突然前扑咬走→重新抱胸嘴硬，鼓腮偷嚼还盯下一颗。',
    firstFrame: '便宜木茶几与塑料水果盒；角色抱胸偏头，观众手在边缘捏草莓，离嘴尚有距离。',
    popularity: '站内收录日期 2026-06-28；未见该条公开播放、下载或转发量。',
    boundary: '没有观察到原图被抓或逃跑结局；拒绝再扑食的三段反转为原创，也未声称此备选已经出图。',
  },
];
