import type { MotionTemplate } from './video';

const motion='Use snappy pose-to-pose character comedy with a short anticipation, a decisive whole-body action and a sharply held change of expression. Every prop movement has visible contact and a cause. Brief drawn squash, stretch and motion smears accent the action, then recover the approved silhouette immediately. Keep the face legible at sticker size. Ordinary room details stay stable while the character acts; no idle swaying or continuous camera shake.';
const noPartner='Only the main character is visible; the viewer is implied by direct eye contact with the lens.';

/** Everyday settings are separate first-frame recipes, not alternate prompts for one image. */
export const everydayTheatreTemplates:MotionTemplate[]=[
  {
    id:'theatre-duvet-ambush',name:'掀被子炸毛，抢回去继续睡',category:'日常炸毛',emoji:'☾',caption:'谁准你掀的！',
    hook:'被角刚拉开就弹起来抗议，抢回被子把自己裹好，只留一双瞪你的眼睛。',
    scene:'A miniature character is tucked into an ordinary unmade bed, on a slightly creased pillow beneath a washed blue-gray checked cotton duvet. The duvet reaches the shoulders; the head and existing hair or appendages rest visibly above its edge. The lived-in bedroom has plain walls, a charging cable near the bedside and everyday slippers low in the background. One realistic adult viewer hand at the lower-right edge already holds a corner of the same duvet, ready to pull it toward the foreground. Natural household light, ordinary bedding and believable fabric creases; no hotel styling or decorative showroom furnishings.',
    pose:'Rest the head on the pillow with sleepy half-open eyes and a mildly annoyed brow aimed toward the viewer. Both {{grip}}s are already visible loosely holding the top duvet edge near the shoulders. The character is fully dressed in the approved original outfit underneath, with unchanged clothing coverage. The duvet is loose enough to move without dragging the pillow or body.',
    beats:[
      'The already-visible viewer hand gives the held duvet corner one quick tug toward the foreground. The character releases both loose grips in surprise, letting the top edge lower from the shoulders to the lap, opens the eyes wide and snaps the gaze toward that hand. Reveal only the same fully clothed character; the original outfit stays fastened and unchanged.',
      'Pop the upper body upright from the pillow in one indignant sit-up, with the lower body still supported by the bed and covered by the duvet. Throw both {{arm}}s outward in a short emphatic protest, mouth open in a silent complaint, brows sharply lowered. Existing hair or appendages spring after the body and settle with a small delay.',
      'Immediately grab the near top edge of the same duvet with both {{grip}}s and yank it back toward the chest. At the start of the yank, the viewer hand releases its corner and retreats out through the lower-right edge. The duvet slides and bunches along the mattress without becoming a second blanket; the character flops backward onto the same pillow while pulling it up.',
      'Finish tucked back in with the duvet drawn just below the eyes, hiding the lower face but leaving both eyes and the top of the head visible. Hold a fierce sleepy stare at the viewer, then narrow the eyes once as if warning against a second attempt. Keep the two grips visibly securing the top edge near the cheeks; the duvet and body settle instead of resetting to the original exposed face.',
    ],
    sound:'One quick cotton swish as the duvet is tugged, a soft mattress thump at the sit-up, a louder bundled-fabric rustle as it is snatched back, then a soft pillow landing and quiet room tone. No speech, vocalization or music.',
    check:'先掀被角才坐起；抢回的是同一条被子。衣服始终完整，最后用被沿藏脸、只露生气的眼睛，不能站到床上原地抖。',loop:false,
    theatre:{edition:2,motive:'起床气比个头还大，最想保住自己的被窝。',trigger:'观众已经抓住被角，突然往外一拉。',payoff:'气势汹汹地抗议完，第一件事还是钻回被子里瞪你。',labels:['被角被拉开','弹起炸毛','一把抢回来','缩回去瞪你'],ends:[.14,.43,.76,1],camera:'Hold a steady bedside camera at pillow height, angled slightly down only enough to show the duvet contact. Keep the hand, character face and moving duvet edge in the same shot; no dramatic zoom or low angle.',secondaryActor:'Exactly one realistic adult viewer hand is already present at the lower-right edge holding the duvet corner. It tugs once, releases when the character takes the duvet back, and withdraws along the same path. No other person appears.',actionStyle:motion,framing:'Square close-medium bedside view. The face occupies enough of the upper-middle frame to read the sleepy eyes; include the pillow, shoulder-height duvet edge and viewer hand in the lower-right foreground. Leave clear space above the head for the sudden sit-up. Keep bedside clutter peripheral and unobtrusive.',gif:[0,1]},
  },
  {
    id:'theatre-cheek-retaliation',name:'捏脸反抗，弹回一张气鼓鼓',category:'屏幕互动',emoji:'☞',caption:'不许捏我！',
    hook:'被捏脸气得双手推开，刚想得意，脸颊却“啵”地弹回一张包子脸。',
    scene:'The small character sits upright on an ordinary slightly worn gray fabric sofa, with a small cushion resting across the lap. A folded household blanket, a plain remote control and a soft tissue packet sit farther back on the sofa, clear of the action. One realistic adult viewer hand enters from image right at cheek height and is already very gently pinching only the cheek on that side between thumb and index finger. The skin or soft rendered cheek is only lightly drawn sideways; the fingers do not cover the eyes or mouth. Use modest lived-in household lighting and clear photographic sofa weave.',
    pose:'Sit firmly on the sofa seat with the small cushion supported by the lap. Turn a grumpy sideways stare toward the attached viewer hand, brows lowered and lips pushed into a reluctant pout. Raise both free {{grip}}s in front of the body in protest, close enough to reach the viewer fingers. Keep the face fully readable and the original costume and proportions intact.',
    beats:[
      'Hold the already-pinched cheek for one very short indignant beat. The brows drop hard, both free grips open toward the hand and the torso leans forward in a decisive wind-up. The viewer does not pull the cheek farther or squeeze harder.',
      'Plant both {{grip}}s against the near side of the viewer fingers and give one brisk two-limb shove toward image right. At contact the thumb and index finger immediately open and release the cheek; the coherent hand retreats to the right and exits. The character follows the shove with the shoulders, then stops securely on the sofa without falling. The small cushion remains in the lap.',
      'Let the released cheek make one quick drawn elastic rebound, returning inward and briefly puffing both cheeks into a round irritated pout. The character had begun lifting the chin triumphantly but freezes at the ridiculous puffed face; wide eyes dart toward the viewer. For a rigid-faced character, show this rebound as a cheek-shaped expression on the existing display rather than bending rigid hardware.',
      'Press both {{grip}}s lightly against the own cheeks once to recover the approved face shape, then drop them onto the lap cushion. Fold the torso into an exaggerated huff, turn the face away and look back at the viewer from the corners of the eyes. Finish with one small stubborn chin lift, still trying to look formidable. No second viewer hand returns.',
    ],
    sound:'A short sleeve and sofa rustle during the shove, one soft cartoon pop when the cheek rebounds, then a quiet cushion rustle. No speech, vocalization or music.',
    check:'开场只有一只手捏一边脸；双手推开后观众手就退场。回弹只发生一次，脸马上恢复，抱枕不能漂走或突然消失。',loop:false,
    theatre:{edition:2,motive:'最讨厌被当成可爱小家伙，却越反抗越像气鼓鼓的小包子。',trigger:'观众轻轻捏住她一边脸，正好戳中她的面子。',payoff:'终于把手推走，得意表情却输给了脸颊的一次回弹。',labels:['憋着火瞪手','双手推开','脸颊啵地回弹','扭头装厉害'],ends:[.1,.43,.67,1],camera:'Keep a fixed character-eye-level medium view. Let the short two-limb shove read through actual shoulder movement and hand contact. Preserve enough side space for the single viewer hand to retreat completely; no camera recoil.',secondaryActor:'Exactly one adult viewer hand is already gently pinching one cheek at the start. Its thumb and index finger remain attached to one coherent palm and wrist. It releases when pushed and immediately withdraws through image right. The contact is harmless and leaves no marks.',actionStyle:motion,framing:'Frontal medium-close composition on the sofa. Include the complete face, both free grips, the viewer thumb and index finger, and the small lap cushion. Reserve room at image right for the hand withdrawal. Show enough torso to read the shove and huff while keeping the face large; no cropped eyes.',gif:[0,1]},
  },
  {
    id:'theatre-door-deadpan',name:'无语关门，还要回来瞪你',category:'无语退群',emoji:'▯',caption:'这个群没救了',
    hook:'看完群聊先关门，越想越不放心，又打开一条缝补你一眼。',
    scene:'The viewer looks from a room toward an ordinary rented-home hallway through a partly open scuffed white wooden door. The panel occupies image right and the open gap is to the left of its free edge; its hinges remain farther right outside the main action. The character is on the far hallway side, behind the door, peeking around that edge with only one eye, part of the cheek, curled hair or existing appendages and one gripping limb visible. The door hides the entire torso and lower body. Beige floor tiles, ordinary slippers, a cheap shoe rack and an umbrella near the entry door establish a modest lived-in home. One {{grip}} holds the reachable edge below the cheek; any visible door hardware remains untouched. Preserve the doorjamb, hinge direction and threshold.',
    pose:'Peek with just one half-lidded eye and a sliver of the face around the door edge, wearing a flat exhausted stare and small straight mouth. Keep one {{grip}} wrapped around the same edge beneath the cheek, with the rest of the body safely behind the door on its far side. Do not reveal the hidden torso or feet.',
    beats:[
      'Hold the single visible eye in a flat stare for a short beat, then blink it slowly in unmistakable disbelief. The head retreats behind the panel while the same grip prepares to guide the door edge.',
      'Guide the reachable edge firmly through its closing arc. The same right-hinged door swings leftward across the visible opening until its free edge meets the left jamb, progressively hiding the hallway. The face and gripping limb retreat fully behind the panel before it reaches the jamb. The character remains on the far side; no limb passes through the wood or becomes trapped.',
      'After a brief closed-door pause, pull the same door back just enough to reopen a narrow slit at the left jamb. Reveal only one eye and a sliver of the cheek peeking from behind its free edge. Hold one pointed, judgmental look toward the viewer; do not reveal a second character or a new room.',
      'Blink that one visible eye once as if deciding the situation is still hopeless, retreat fully behind the panel, and guide the door closed again in one short emphatic movement. End on the same closed white door and stable threshold for a brief comic deadpan hold; the final closure is physical movement, not a cut to a still frame.',
    ],
    sound:'A brief hinge creak and one soft wooden closing thunk, a quiet pause, another small hinge creak as the slit reopens, then a second slightly firmer wooden thunk. No speech, vocalization or music.',
    check:'从首帧现有门边发力，不换手去够门锁。两次关门都先收回头和手；开缝时只露一只眼，门轴方向不能反转。',loop:false,
    theatre:{edition:2,motive:'想体面退出这场离谱聊天，却忍不住回来确认你有没有更离谱。',trigger:'隔着门缝看到观众，露出“我都看到了”的无语表情。',payoff:'门已经关上，还要专程开条缝补一眼，然后再关一次。',labels:['无语看着你','用力关门','开缝补一眼','再关一次'],ends:[.13,.47,.77,1],camera:'Keep a locked eye-height view of the same doorway and its threshold. The door supplies the wipe and reveal; do not move the camera, cut away or zoom through the door.',secondaryActor:noPartner,actionStyle:motion,framing:'Square eye-level view with the scuffed white door panel on image right and the hallway opening to the left of its free edge. Frame only a large expressive partial face, existing hair or appendages, and one gripping limb peeking around that edge; the door completely conceals the torso and lower body. Show ordinary hallway details around the face. Keep the far-right hinge placement and left closing jamb consistent.',gif:[0,1]},
  },
  {
    id:'theatre-medal-praise',name:'举奖牌讨夸，直接怼到你眼前',category:'求夸贴脸',emoji:'★',caption:'快夸我！',
    hook:'抱着小奖牌等不到夸奖，干脆迈过来举到你眼前，还从旁边探脸催你。',
    scene:'A miniature character stands on an ordinary worn light-laminate computer desk, holding one cheap chunky gold star-shaped medal with a red ribbon in both {{grip}}s at the upper torso. An older black keyboard and black mousepad stay behind. A partly empty clear plastic drinking cup, one wrinkled unlabelled snack wrapper and a loose white charging cable sit around the edges, leaving a clear path toward the camera. This is a lived-in everyday desk with modest room lighting, not a showroom or gaming advertisement. The solid medal has a plain star face without lettering; its same red ribbon remains attached and looped around the neck.',
    pose:'Stand with both feet planted and one foot slightly forward, holding the single star medal securely by its two lower sides. Keep it just below the chin so the full expectant grin and bright eyes remain visible. Lean forward a little, raise the eyebrows and look straight at the viewer, visibly waiting to be praised. The medal and ribbon are separate from the character own permanent accessories.',
    beats:[
      'Raise the medal a tiny amount to present it, lift the eyebrows and wait one short expectant beat. When no response comes, the smile tightens into an impatient little pout and one foot lifts to begin a deliberate approach.',
      'Take two brisk high-kneed marching steps along the clear desk toward the lens, actually moving the whole body closer while holding the same medal securely. Each foot visibly lands and pushes off; the red ribbon bounces behind the medal without tangling. The keyboard recedes behind through the approach and stays stationary on the desk.',
      'Plant both feet and lean forward while thrusting the star medal in both {{grip}}s until it becomes large in the near foreground, stopping just short of the lens. Reach only as far as the existing neck ribbon allows; it stays looped around the neck without stretching or detaching. Keep both grips attached to its lower sides and preserve the star shape. Lean the head out around the left side of the raised medal, opening into an exaggerated showy grin as if insisting that the viewer look properly.',
      'Hold the medal close and steady, then move only the head to peek around its other side with raised brows and an unmistakable expectant pout. End with the face clearly visible beside the medal, one confident chin lift and direct eye contact, proudly waiting for applause. The medal never strikes the camera, duplicates or hides the face for the whole payoff.',
    ],
    sound:'Two quick light desk footfalls, a small medal-and-ribbon jingle with the forward thrust, then a short ribbon rustle as the final pose settles. No applause track, speech, vocalization or music.',
    check:'两步真的走近，再举到镜头前；奖牌始终一块、红绳始终连着。最后探脸讨夸是重点，不能变成站桩举牌。',loop:false,
    theatre:{edition:2,motive:'一点小成就也想第一个告诉你，偏偏还要装作自己早就知道很厉害。',trigger:'举着奖牌等了半拍，观众居然还没夸。',payoff:'怕你装没看见，奖牌直接递到眼前，人还从两边探出来催夸。',labels:['等你夸半拍','两步走到面前','奖牌举到眼前','探脸催夸'],ends:[.12,.43,.7,1],camera:'Keep a fixed frontal camera at the character eye level. The face and medal grow larger because the character physically walks and reaches toward the lens, not because of a zoom. Keep the near medal and the face peeking beside it readable together.',secondaryActor:noPartner,actionStyle:motion,framing:'Eye-level medium-full opening shot with both feet visible and character about two thirds of frame height. Leave a clear foreground strip of desk for two short steps, and enough horizontal space for the face to peek around either side of the medal after approaching. Keep desk clutter behind or outside the walking path.',gif:[.04,1]},
  },
];
