import type { MotionTemplate } from './video';

const motion='Use clear pose-to-pose character comedy with lively eye contact, a committed change in distance and a readable reversal of intention. Contrast a quick decisive gesture with one brief held expression. Every prop transfer and touch has visible contact and release. Existing hair, ears and clothing follow the action with delayed settling; recover the approved silhouette after any brief drawn smear. Keep the original costume, coverage, accessories and body proportions unchanged. Convey personality through the face, hands and everyday situation. No idle swaying, repetitive petting loop, camera shake or added anatomy; adapt finger gestures to the existing paw or gripper when necessary.';
const noPartner='Only the referenced main character is visible. The viewer is implied by direct eye contact with the lens; no viewer hand or additional character appears.';

/** Each personality skit has an independent first-frame pose and contact setup. */
export const personalityTheatreTemplates:MotionTemplate[]=[
  {
    id:'theatre-beckon-boop',name:'招你靠近，趁机戳你鼻尖',category:'淘气逗你',emoji:'☞',caption:'你还真过来呀',
    hook:'笑着勾手让你靠近，自己也凑过来，突然轻戳一下鼻尖，再缩回去一脸得逞。',
    scene:'The small character sits securely behind an ordinary real pale-wood or cream dining tabletop, which naturally conceals the lower body. One {{grip}} is planted on the near tabletop for support. The other is raised beside the face with its index loosely curled inward, ready to beckon; use an equivalent motion of an existing paw or gripper if the character has no fingers. The complete face is large and unobstructed, with clear space between the character and lens for a short forward lean. The modest everyday dining room and photographic table stay still, without decorative props in the motion path.',
    pose:'Look directly at the viewer with half-lidded mischievous eyes and a little knowing grin. Keep the raised {{grip}} beside, rather than across, the cheek and the other firmly supported on the table. Sit upright in the approved original outfit, preparing a playful invitation without already touching the lens.',
    beats:[
      'Make exactly two quick inward beckoning curls with the raised index or existing grip tip. Keep the eyes fixed on the viewer and lift one eyebrow as the smile grows, making the invitation and hidden joke readable. The other {{grip}} remains planted on the tabletop.',
      'Slide the supporting grip a short distance forward along the table and lean the upper body toward the lens from the stable seated position. The face becomes noticeably larger through actual movement, with bright direct eye contact and the beckoning grip still beside the cheek. Do not zoom or reveal the hidden lower body.',
      'Extend that same raised {{arm}} toward the lens and give one gentle poke at the image plane, as if touching the viewer nose. The single fingertip or compatible grip tip briefly foreshortens in the near foreground and stops at contact; accent it with one small soft contact pop. Keep the eyes visible beside it, with no second poke, viewer hand, camera recoil or prolonged face obstruction.',
      'Immediately withdraw the poking grip along the same path and rest its tip against the own cheek. Lean back into the original seated support, open into delighted laughing eyes and then give one smug wink at the viewer. End on a visibly pleased caught-you grin, keeping the full face clear. No kiss or additional contact follows.',
    ],
    sound:'Two light sleeve rustles, a soft tabletop slide during the approach, one tiny rounded cartoon contact pop at the single nose poke and a short clothing swish on retreat. No speech, laughter vocalization or music.',
    check:'勾两下手再真正凑近，只戳镜头一次；指尖马上撤回自己的脸旁，最后得逞眨眼，不能一直挡住脸。',loop:false,
    theatre:{edition:2,motive:'最喜欢把观众逗过来，再让对方发现自己中了一个小圈套。',trigger:'观众正看着她，刚好可以用一个勾手把注意力牢牢抓住。',payoff:'邀请靠近是为了轻戳一下，缩回去还要用得意眨眼承认自己故意的。',labels:['笑着勾手两下','自己也凑过来','轻戳一下鼻尖','缩回去得意眨眼'],ends:[.2,.43,.62,1],camera:'Hold a fixed frontal camera at the seated character eye height. Let the face grow through a supported forward body lean, then shrink naturally on retreat. Keep enough near space for a single foreshortened fingertip contact; no zoom, cut or camera reaction.',secondaryActor:noPartner,actionStyle:motion,framing:'Square close-medium frontal view with a large complete face, both grips and the near dining-table edge visible. The table conceals the lower body. Reserve clear foreground distance for the short lean toward the lens, plus side room beside the cheek for the raised grip and its retreat. Keep the eyes readable throughout the brief contact.',gif:[0,1]},
  },
  {
    id:'theatre-bag-date',name:'以为要牵手，结果是帮她拎包',category:'甜笑小算盘',emoji:'♧',caption:'那就拜托你啦',
    hook:'手都甜甜地伸过来了，下一秒却把小包挂到你手上，自己背着手眨眼装乖。',
    scene:'A miniature character stands on a broad ordinary wooden hallway bench beside a home entrance, with both shoes supported on the bench. The character image-left {{grip}} holds one small plain black handbag at the side by its short curved handles held together; the bag hangs below the waist and is small enough for easy transfer. The other free {{grip}} reaches toward exactly one realistic adult viewer hand entering from the lower-right edge. That coherent viewer hand is palm-up at bench height, fingers relaxed and still separate from the character. A simple key tray and everyday slippers sit farther back, leaving the bench surface open and the bag-transfer path clear.',
    pose:'Stand balanced with both feet visible, half-lidded bright eyes and a sweet little scheming grin aimed at the viewer. Keep the black bag suspended from the image-left grip, its existing handles clearly visible. Extend the free grip toward the waiting open palm without touching it yet, as if about to accept a friendly handhold.',
    beats:[
      'Lean slightly toward the waiting viewer palm and extend the free {{grip}} a little farther, smiling expectantly as if about to take the offered hand. Stop just short of palm contact. Keep the handbag attached to the other grip and both feet planted on the bench.',
      'Change the plan at the last moment: move the free grip over to guide the handbag handles together while the bag-holding {{arm}} brings the same bag toward the viewer. Lower those same handles together onto the viewer gently curled index and adjacent fingers, which form one supporting hook above the open palm. Both character grips guide this single transfer; the bag follows the handle without teleporting.',
      'Let the viewer fingers close securely around both handles while the wrist stays at the lower-right edge at bench height. After the same bag visibly hangs from the viewer grip, release both character grips and draw them away. The viewer hand continues carrying the bag in the lower-right foreground; no second bag, extra hand or unsupported floating handle appears.',
      'Put both now-empty {{grip}}s behind the own back, lean the upper body toward the viewer from the planted feet and give one cheerful wink. Finish with raised chin and a proud little innocent-looking smile, as if carrying the bag had always been the arrangement. The viewer remains holding the same bag, and the character does not take it back.',
    ],
    sound:'A small clothing rustle during the reaching feint, a soft handbag-handle creak as the weight transfers and a brief sleeve swish as both hands move behind the back. Quiet hallway ambience; no speech, vocalization or music.',
    check:'开场她拿一只包、观众只伸一只掌心朝上的手；必须先把提手交稳才松开。最后空手背到身后，包仍在观众手里。',loop:false,
    theatre:{edition:2,motive:'想让观众帮忙，又偏要先用一个甜甜的邀请卖关子。',trigger:'观众正好伸出一只等着回应的手，她立刻想到自己的小包。',payoff:'看似要牵手，实际把包交出去，自己还装乖眨眼说服你认下这份差事。',labels:['甜笑伸手像要牵','临时改成交小包','交稳提手才松手','背手眨眼装无辜'],ends:[.18,.49,.7,1],camera:'Use one locked frontal three-quarter view at the miniature character eye height. Keep the whole handover and both planted feet visible together. The viewer wrist remains attached to a hand entering from the same lower-right edge; no camera move, cut or close-up insert.',secondaryActor:'Exactly one realistic adult viewer hand enters from image lower right and is already waiting palm-up at bench height. During the transfer, its attached index and adjacent fingers curl into a supporting hook, then close around the handbag handles. The coherent hand and wrist remain visible at that edge holding the bag for the ending. No other person or hand appears.',actionStyle:motion,framing:'Square medium-full view of the broad bench, both character shoes and one small black handbag. Keep the character slightly left of center and the open viewer palm in the lower-right foreground with a visible attached wrist. Show the original curved handles between them without overlapping the face. Leave enough room for a forward upper-body lean after transfer, while keys and slippers remain peripheral.',gif:[0,1]},
  },
  {
    id:'theatre-rose-sneeze',name:'玫瑰都递好了，自己先打个喷嚏',category:'耍帅翻车',emoji:'✿',caption:'才、才没失误',
    hook:'拿玫瑰眨眼还挺像回事，花刚递近就忍不住打喷嚏，发侧挂着花瓣还要装镇定。',
    scene:'The fully dressed small character sits behind a modest household balcony table covered with a plain pale-gray cloth, naturally concealing the lower torso and body. The image-left {{grip}} holds exactly one long-stem pink rose upright beside the face at shoulder height, gripping the stem below the bloom. The other grip rests on the tabletop. A mundane plant pot and a laundry rack are softly visible far behind in natural daylight. Keep the face unobstructed, the rose separate from the cheek and a clear foreground path for offering it. This is an ordinary lived-in balcony, with no additional bouquet or decorative staging.',
    pose:'Sit upright, looking at the viewer with a playful confident smile. Hold the single pink rose upright beside the shoulder in the image-left grip, its bloom beside the cheek and clear of the eye and its long stem clearly attached. Keep the other {{grip}} resting on the table, ready to support a quick reaction. Preserve the original outfit and accessories.',
    beats:[
      'Bring the rose bloom beside the cheek without covering the eye and give the viewer one deliberate wink. Lift the chin slightly in an overconfident presentation, with the free grip still resting on the table and the same stem held securely.',
      'Extend the rose-holding {{arm}} toward the lens, offering the single bloom into the near foreground with bright confident eye contact. Lean forward just enough to follow the gift while remaining securely seated. The rose stays in the original grip, and its stem and flower head remain connected.',
      'The nose twitches and the confident face suddenly tightens. Pull the held rose back to the side to clear the face, then turn into the free {{arm}} and perform one large silent cartoon sneeze into that forearm. The head and shoulders jerk once; existing hair or appendages fluff outward and immediately settle. One pink petal loosens from the same rose, briefly flutters sideways outside the eye line and catches in the hair beside the temple, or on the existing side-of-head surface. Keep the rose in its grip and add no other petals.',
      'Lower the free forearm and freeze for a short embarrassed wide-eyed beat, with the single petal still caught beside the temple. Then lift the chin, recover a small determined composed grin and look back at the viewer as if nothing went wrong. Keep the rose upright beside the shoulder; the petal stays visible and unnoticed as the final joke.',
    ],
    sound:'A faint rose-stem and sleeve rustle during the offering, one short physical air-and-cloth whoosh from the sneeze-like motion, then quiet balcony room tone. No spoken sneeze, voiced exclamation, speech, other vocalization or music.',
    check:'只递一支玫瑰；打喷嚏前先把花拉到侧边，用空着的前臂挡一下。只掉一瓣并挂在发侧，结尾强装镇定时花瓣还在。',loop:false,
    theatre:{edition:2,motive:'想靠一朵玫瑰把气氛拿捏住，最好让观众觉得自己十分从容。',trigger:'递花时鼻子突然发痒，正好赶在最想装帅的一刻。',payoff:'刚恢复镇定，发侧那片花瓣却替观众记住了这次翻车。',labels:['花贴脸旁眨个眼','自信递到你面前','喷嚏把自己出卖','挂着花瓣装镇定'],ends:[.19,.42,.73,1],camera:'Use one fixed frontal close-medium view at the seated character eye height. Show the rose offering, its withdrawal to the side and the free forearm reaction in one shot. Keep the brief hair bounce controlled and reserve space beside the temple for one petal flutter; no zoom, cut or camera shake.',secondaryActor:noPartner,actionStyle:motion,framing:'Square balcony-table close-medium composition with the full face, both grips and upper stem of the single rose visible. The pale-gray table naturally conceals the lower body. Reserve clear space beside the image-left shoulder for the rose to withdraw, beside the face for the single fluttering petal and in the foreground for a short offering gesture. The distant plant pot and laundry rack stay softly legible.',gif:[0,1]},
  },
  {
    id:'theatre-headpat-demand',name:'不许摸头，但也不许停',category:'嘴硬讨宠',emoji:'♡',caption:'谁让你停了',
    hook:'刚摸一下就装凶推开，手真退走又不乐意，抓回来顶着手心，还要偷看你。',
    scene:'The small character sits securely in the corner of a plain beige household sofa, with a faded blue square cushion resting on the lap. The complete expressive face is large above the cushion. Exactly one realistic adult viewer hand enters from image upper right and hovers just above the existing hair or crown, with an attached visible wrist and a relaxed open palm; there is no contact yet. One character {{grip}} is loosely raised near that wrist, ready to ward it off, while the other rests on the lap cushion. Keep the sofa weave, cushion and ordinary room lighting stable, with clear room at upper right for a short hand withdrawal.',
    pose:'Sit upright with half-lidded eyes, a small stubborn pout and a sideways look toward the hovering viewer hand. Keep the raised grip relaxed within reach of the same wrist and the other grip visibly supported by the faded blue cushion. The lap cushion stays supported by the seated body; the approved original outfit and proportions remain unchanged.',
    beats:[
      'The already-visible viewer hand lowers its relaxed palm and gives the existing crown one gentle brief pat. Hair or soft head material compresses lightly and springs back; rigid parts remain rigid. The character eyes soften for an instant, then the brows tighten as if remembering to look annoyed.',
      'Place the raised {{grip}} against the side of that same viewer wrist and give one light decisive push toward image upper right. The viewer hand immediately lifts clear of the crown and yields, remaining connected to the same visible wrist. The character raises the chin and holds an exaggerated offended glare, while the lap cushion stays in place.',
      'As the viewer hand retreats a little farther toward upper right but stays visible and within reach, the character face drops into unmistakable disappointment. Abruptly lean forward and lift both {{grip}}s to grasp the same wrist gently, guiding that one open palm back above the crown. Maintain a coherent hand and wrist throughout; the movement is a short guided return, not a yank or a new hand entering.',
      'Once the open palm is above the crown, release the wrist with both character grips and rest them back on the lap cushion. Push the crown upward into that waiting palm once with a small delighted body stretch, closing the eyes in smug contentment. Settle under the still palm, then open one eye sideways for a tiny checking peek as if making sure the viewer understands. No repeated patting follows.',
    ],
    sound:'One soft hair-and-palm brushing sound, a brief sleeve rustle during the push and guided return, and a small cushion rustle as the character settles. Quiet living-room ambience; no speech, vocalization or music.',
    check:'一只观众手先摸一下再被推开，始终留在右上方可够到。她用双手拉回同一手腕后先松手，才主动顶一下手心；不拽头发、不循环摸头。',loop:false,
    theatre:{edition:2,motive:'喜欢被在意，却又不肯承认自己很享受这点宠爱。',trigger:'观众伸手轻轻摸一下，刚好让她想起要维持自己的小脾气。',payoff:'嘴硬推开是真的，舍不得停也是真的，最后干脆自己把头顶回手心。',labels:['摸一下差点露馅','装凶把手推开','真停了赶紧拉回','自己顶上去偷看'],ends:[.19,.41,.75,1],camera:'Hold one fixed frontal three-quarter sofa view at the character eye height. Keep the full face, lap cushion, two character grips and the one viewer hand with its wrist visible. The upper-right retreat remains a short reachable distance; no camera movement or cut.',secondaryActor:'Exactly one realistic adult viewer hand is already hovering above the crown from image upper right. Its relaxed palm pats once, yields to a light wrist push, retreats only a short reachable distance and follows the two character grips back above the head. The wrist stays connected to the same visible hand, whose palm remains still for the final upward head press. No additional person or hand appears.',actionStyle:motion,framing:'Square close-medium sofa composition with the large full face, both character grips and faded blue lap cushion visible. Show one coherent adult viewer hand and attached wrist entering from upper right, leaving a small gap above the crown before contact. Reserve upper-right space for a short withdrawal and enough headroom for the final gentle upward press; keep the entire interaction within arm reach.',gif:[0,1]},
  },
];
