import { comedyReferences } from './comedy-research';

export interface ReactionReference {
  id:string; family:string; title:string; url:string;
  format:string; verification:string; provenance:string; theme:string; uses:string[];
  observed:string; mechanism:string; adaptation:string; firstFrame:string;
  popularity:string; boundary:string;
}
export const researchDate='2026-09-25（洛杉矶）';
const previousReactionReferences:ReactionReference[]=[
  {id:'phoebe-blanket',family:'菲比',title:'掀被子菲比',url:'https://kato-shoko705.github.io/Phoebe-Hub/images/掀被子菲比.gif',format:'GIF 动图',verification:'已看多个动作相位',provenance:'粉丝收集站，原作者未核实',theme:'观众参与',uses:['叫起床','被打断'],observed:'真人手臂掀开浅色被子；另一个相位中，2D 菲比站在床上，张嘴、伸臂、头发炸起。',mechanism:'观众先做一件具体的事，角色才产生夸张反应。',adaptation:'你掀被子→Margaret 炸毛扑回被子→从被边露一只眼继续瞪你。',firstFrame:'床边视角，被角可抓，角色裹在里面；画外手的路径与起身空间都预留。',popularity:'站内收录日期 2026-07-02；没有单图公开转发或下载量。',boundary:'看过不同相位，未逐帧计时。收录不等于 QQ 热榜。'},
  {id:'phoebe-food',family:'菲比',title:'干饭菲比_1',url:'https://kato-shoko705.github.io/Phoebe-Hub/images/干饭菲比_1.gif',format:'GIF 动图',verification:'已看多个动作相位',provenance:'粉丝收集站，原作者未核实',theme:'道具事件',uses:['干饭','真香','吃瓜'],observed:'摄影木地板与金属饭盆旁的 2D 小人，一相位举勺望前，另一相位把饭送到嘴边、张嘴鼓腮。',mechanism:'勺子、食物与嘴之间有清楚的路径，道具状态随动作改变。',adaptation:'偷吃一口被看见，立刻把空盘翻过去藏证据，嘴角却还沾着碎屑。',firstFrame:'近景盘子、伸向食物的手、可读的嘴同时出现；不要用抱着道具的正面站姿。',popularity:'站内收录日期 2026-07-02；未见单图传播统计。',boundary:'能支持接触与表演方法，不能证明单条爆款。'},
  {id:'phoebe-taunt-counterexample',family:'菲比',title:'你已急哭（语义反例）',url:'https://kato-shoko705.github.io/Phoebe-Hub/images/你已急哭.gif',format:'GIF 动图',verification:'已看多个动作相位',provenance:'粉丝收集站',theme:'群聊回击',uses:['调侃','回击'],observed:'白底大脸、两手举起、星系特效和“你已急哭”文字；没有看到嚎哭、流泪或捶地。',mechanism:'短句、姿态与脸共同表达对对方的调侃。',adaptation:'可研究得意回击的态度；不能拿这条当“大哭动作”依据。',firstFrame:'针对回击意图设计嚣张眼神和手势，不因标题里有“哭”就画泪水。',popularity:'没有单图公开转发量。',boundary:'文件名不等于画面含义；另有静态及闪光版本，不应混算。'},
  {id:'taffy-punch',family:'塔菲',title:'永雏小菲打喵拳 GIF 表情包',url:'https://www.bilibili.com/video/BV1ih4y1H7a7/',format:'视频取样',verification:'已看发布页视频画面',provenance:'发布者：塔菲亡命天涯',theme:'观众参与',uses:['回击','我超凶'],observed:'正面半身 3D 小菲，桌面与房间背景，双拳朝观看者方向前伸。',mechanism:'拳头有明确观看对象，方向朝观众，脸仍能被看见。',adaptation:'前压蓄力→左右交替冲屏→命中回弹→打疼手后装赢；收尾为本项目创意。',firstFrame:'正面出拳通道、清楚的左右手、前压重心；与凑脸撒娇的首帧分开。',popularity:'2023-04-18 发布；本次页面显示 1.1 万播放、337 赞、68 收藏、37 分享。',boundary:'旧作累计指标，不是近期增速；未完整核验拳速、次数或收势。'},
  {id:'taffy-cry',family:'塔菲',title:'taffy-cry',url:'https://github.com/vegetable-kun/DSH_Plugin_Taffy/blob/main/assets/taffy-cry.gif',format:'GIF 动图',verification:'已看多个动作相位',provenance:'公开素材仓库，原动画作者未确认',theme:'夸张情绪',uses:['委屈','求哄','认输'],observed:'暖色室内的大脸近景，张嘴，双眼下有宽浅蓝泪柱；不同画面中头部位置变化。',mechanism:'大面积泪形和口型缩成小图仍清楚。',adaptation:'让 Margaret 的眉、眼、嘴、踢腿和泪水同时改变，再用突然停住的偷看制造反差。',firstFrame:'大脸与自由双手可见，地面和踢腿空间清楚；不用笑脸抱食物的图。',popularity:'仓库本次为 2 stars、0 forks；没有单条 GIF 播放或转发量。',boundary:'仓库可查性不代表流行度。'},
  {id:'taffy-laugh',family:'塔菲',title:'taffy-tang-laughing',url:'https://github.com/vegetable-kun/DSH_Plugin_Taffy/blob/main/assets/taffy-tang-laughing.gif',format:'GIF 动图',verification:'已看多个动作相位',provenance:'公开素材仓库',theme:'夸张情绪',uses:['笑死','嘲笑'],observed:'蓝色背景的粉发极近大脸，弧线眼、露出整排牙齿，头部角度与位置在截图间变化。',mechanism:'笑脸本身就有喜剧形状，不能只给日常漂亮脸增加晃动。',adaptation:'憋笑失败时先改变眉眼嘴，再让全身侧倒；打滚是我们另写的剧情。',firstFrame:'已经快憋不住的脸、手扶肚子或遮嘴；给侧倒留路径。',popularity:'仅核验被公开收录，没有单图使用量。',boundary:'没有在原图中看见打滚，不把文件名扩写成已观察动作。'},
  {id:'taffy-fake-counterexample',family:'塔菲',title:'taffy-fake_crying（命名反例）',url:'https://github.com/vegetable-kun/DSH_Plugin_Taffy/blob/main/assets/taffy-fake_crying.gif',format:'GIF 画面',verification:'已看画面，周期未确认',provenance:'公开素材仓库',theme:'群聊回击',uses:['夸张认输','我没了'],observed:'黑色粗边框与缎带构图，框内是闭眼张嘴的塔菲；取样画面接近。',mechanism:'构图本身可以参与语义。',adaptation:'可研究夸张“我没了”的表达；不据此生成“抹泪偷看”脚本。',firstFrame:'先确定要回复的群聊意思，再决定是否需要框或道具，不照搬名字。',popularity:'没有单图可核验传播量。',boundary:'本次没有确认完整动作链，明确不是假哭偷看的实证。'},
  {id:'deepseek-caught',family:'DeepSeek 娘',title:'#1417 工作—摸鱼—惊醒—装乖',url:'https://www.aigengtu.com/en#/meme/1417',format:'静态四格',verification:'四格全图已查看',provenance:'粉丝梗图库，图作者未确认',theme:'抓包装乖',uses:['摸鱼','心虚','被抓包'],observed:'电脑前笑着打字→趴键盘睡着→红色报错屏前惊醒摊手→双手握在一起装无辜。',mechanism:'同一角色前后行为矛盾，环境留下被抓包的后果。',adaptation:'偷懒被叫到→突然挺直→假装一直认真；键盘要产生事件，不能只敲一下。',firstFrame:'正在偷偷躺平、下一拍将被叫醒的状态；屏幕和手的位置能承接反应。',popularity:'页面未提供该图独立下载或转发量。',boundary:'这是漫画叙事参考，不是 GIF，也没有动画速度数据。'},
  {id:'deepseek-denial',family:'DeepSeek 娘',title:'才不是蓝色大肥鱼呢！',url:'https://www.bilibili.com/video/BV1BtND69Euf/',format:'视频取样',verification:'已看发布页画面',provenance:'作者：狐光便利店；简介标注 AI 制作及形象来源',theme:'观众参与',uses:['嘴硬','委屈否认'],observed:'水彩漫画画面中，画外手指向跪坐小角色，她眼含泪、撇嘴，旁边有空碗。',mechanism:'逗弄针对角色发生，反应有对象；空碗说明她的处境。',adaptation:'根据 Margaret 自己的好胜与想被偏爱设计一句被戳中的话，再让她嘴硬回应。',firstFrame:'可读的脸、被指向的方向与处境道具同时存在。',popularity:'2026-07-14 发布；本次为 34.3 万播放、5.1 万赞、1.5 万收藏、489 分享。',boundary:'视频互动量不是 GIF 转发量；没有声称全程都是静态图。'},
  {id:'deepseek-bawl',family:'DeepSeek 娘',title:'005_bawl 喷泉泪',url:'https://github.com/DejavuMoe/deepseek_wale_girl/blob/master/gifs/005_bawl.gif',format:'GIF 画面',verification:'构图已查看，节拍未测',provenance:'作者仓库：Dejavu Moe',theme:'夸张情绪',uses:['大哭','求安慰'],observed:'跪坐大头、双拳在胸前、大张嘴，两股粗蓝泪流落成水洼，下有“大哭”文字框。',mechanism:'情绪变成夸张、可辨认的几何形状。',adaptation:'借泪流形状，但让 Margaret 另有捶地、停哭、偷看这条事件链。',firstFrame:'脸与双手无遮挡，地面能承接泪水；避免所有效果糊成一片。',popularity:'仓库本次为 14 stars、0 forks；作者称整库 104 款、512×512、8 帧。',boundary:'规格是作者声明，未逐文件验算；刚发布数天不能称 QQ 爆款。'},
  {id:'usagyuuun-bawl',family:'Usagyuuun',title:'Usagyuuun 4 · 夸张喷泪',url:'https://store.line.me/stickershop/product/5907346/en',format:'动态贴图',verification:'官方标注动态＋预览已查看',provenance:'Minto 的 LINE 商品页',theme:'夸张情绪',uses:['崩溃','笑死','安慰'],observed:'预览中兔子横趴、脸朝下，大股蓝泪冲向地面；同组还有仰面喷水泪、瘫倒和安慰同伴。',mechanism:'整个人的极端姿态与泪水共同说明情绪。',adaptation:'张嘴、后仰、踢腿、攥拳、泪流同步爆发；真实地面承接效果。',firstFrame:'身体已在憋不住的极端起势，留下地面与泪水落点。',popularity:'此包未公开销量或转发数。Minto 全公司贴图下载合计不能当作单包数据。',boundary:'没有逐帧测量速度，不给原动画编造精确频率。'},
  {id:'betakkuma-body',family:'Betakkuma',title:'Aggressive Bear Betakkuma 19',url:'https://store.line.me/stickershop/product/25187563/en',format:'动态贴图',verification:'官方标注动态＋预览已查看',provenance:'Minto 的 LINE 商品页',theme:'全身喜剧',uses:['得意','回应','庆祝'],observed:'打开过绿色椅子上的“いいね”预览：熊头配长肢体，坐椅翘腿、一手举高；其他格有侧躺、叉腰伸臂。',mechanism:'可爱脸与过分认真的全身行为形成反差。',adaptation:'借认真得过头的身体表演，让 Margaret 扭转重心、出拳回弹，保留自己的身形。',firstFrame:'整个重心和肢体轮廓读得清，别只给胸前手部留一小块空间。',popularity:'该包未公开销售、观众或发送量；含 2024 年题材，并非新热榜证据。',boundary:'预览姿势不等于已分析完整动作周期，不复制其长肢体造型。'},
  {id:'milkmocha-pinch',family:'Milk & Mocha',title:'Angry Sweat · 拉脸互动',url:'https://giphy.com/stickers/angry-pissed-off-milkmocha-L3iXjPw1GoEk0nioqY',format:'GIF 动态贴图',verification:'画面已查看',provenance:'GIPHY 认证 milkmochabear',theme:'观众参与',uses:['闹别扭','被欺负','嫌弃'],observed:'白熊气鼓鼓拉长棕熊一侧脸颊，棕熊受力偏向一侧并无奈冒汗。',mechanism:'接触、受力与两方不同的表情构成关系。',adaptation:'Margaret 想保持凶脸，脸却被轻捏变形；松手后马上鼓腮还嘴硬。',firstFrame:'脸、接触方向与一个连着手腕的手同时可读；为形变留空间。',popularity:'本次页面为 484,828,773 Views；属于 GIPHY 累计服务展示计数。',boundary:'不等于独立用户、主动转发数或 QQ 热度；未据此承诺爆火。'},
  {id:'milkmocha-heart',family:'Milk & Mocha',title:'My Love Hearts · 抱大爱心',url:'https://giphy.com/stickers/love-hearts-milk-kfRKF0iqA8jyDqq1nH',format:'GIF 动态贴图',verification:'画面＋可访问描述已查看',provenance:'GIPHY 认证 milkmochabear',theme:'亲近撒娇',uses:['抱抱','喜欢你'],observed:'白熊趴抱在大粉色爱心上；页面描述明确包含大爱心弹动和两颗小爱心交替弹动。',mechanism:'身体与道具的接触成为整个表情。',adaptation:'先把抱枕推到你面前求抱，等不到回应就自己扑上去，抱枕被压扁。',firstFrame:'可压的抱枕、伸向观众的手与扑过去的空间，不能沿用护食站姿。',popularity:'本次页面为 10,376,210,135 Views；仍为 GIPHY 平台累计口径。',boundary:'文字描述支持弹动关系，未做逐帧速度测量。'},
  {id:'peach-emotions',family:'蜜桃猫',title:'Mochi Mochi Peach Cat Emoji',url:'https://store.line.me/emojishop/product/64814d48b74fae74142e7170/en',format:'动态 Emoji',verification:'官方标注动态＋预览已查看',provenance:'BU JUE XIAO XIAO 官方 LINE Emoji',theme:'群聊功能',uses:['大哭','无语','偷偷看'],observed:'大哭格大张嘴、两束宽泪落成水洼；其他格包含门后露半张脸、墨镜、半闭眼、玩具锤和问号。',mechanism:'同一角色通过清楚的情绪形状承担不同聊天回复。',adaptation:'补“盯你→慢慢关门只露一眼→彻底关上”的无语位，避免整套全是翻车装乖。',firstFrame:'门、把手、可探出的脸以及关门路径清楚。',popularity:'未查到本套公开销售/发送量；热门列表排序会变，不声称固定名次。',boundary:'把整套看过的姿势和预览范围分开，不推断每格的完整周期。'},
  {id:'momonga-attention',family:'Chiikawa / Momonga',title:'Chiikawa(momonga) · 求关注姿态',url:'https://store.line.me/stickershop/product/32411274/en',format:'静态贴图',verification:'整组姿态已查看',provenance:'nagano 的 LINE 商品页',theme:'亲近撒娇',uses:['求夸','理理我'],observed:'举爪到脸旁求夸、歪头盯人、侧躺、从同伴后方露出及拽物撒娇；含“褒めろッ”等文案。',mechanism:'想被关注是一贯动机，可驱动许多不同动作。',adaptation:'Margaret 举奖牌炫耀后偷看你，不够就把奖牌举到镜头前挡住你。',firstFrame:'炫耀的对象已经出现，目光在道具和观众之间有关系。',popularity:'本次心形区域约 350k，含义不等于购买/发送；没有公开销售量。',boundary:'这是静态性格与姿态参考，不能作为动画节奏证据。'},
  {id:'pusheen-caught',family:'Pusheen',title:'April Fools Dog · 现场证据',url:'https://giphy.com/stickers/sneaky-silly-dog-paper-shredder-ene6dDcs3nuPeYwQbR',format:'GIF 动态贴图',verification:'画面已查看',provenance:'Pusheen 认证 GIPHY',theme:'抓包装乖',uses:['不是我','心虚'],observed:'圆狗坐在倒下的青色垃圾桶旁，地上散着纸，嘴和头上还粘着纸片。',mechanism:'无辜脸与无法抵赖的现场形成矛盾。',adaptation:'空盘、嘴角碎屑、藏不住的饼干都留下，Margaret 却把手放好装无辜。',firstFrame:'让证据能在小图中看清，桌沿与背后的遮挡关系必须有用。',popularity:'本次页面显示 38,801,723 Views。',boundary:'没有看到原图演完整“偷→被抓”链，那个剧情是我们的改编。'},
  {id:'pusheen-attention',family:'Pusheen',title:'Bored Cat · 无聊求陪玩',url:'https://giphy.com/stickers/cat-meow-pusheen-yzR9R9CIXfPvkvQoBi',format:'GIF 动态贴图',verification:'画面已查看',provenance:'Pusheen 认证 GIPHY',theme:'群聊功能',uses:['好无聊','理理我'],observed:'猫侧躺靠着线球、张嘴，上方是夸张的喵叫文字，姿态懒散。',mechanism:'动作可以少，但必须有一句明确的回复或诉求。',adaptation:'Margaret 敲杯两下没人理，就把杯子推到镜头前挡住你，再从杯沿探头。',firstFrame:'近景杯子、可推动的桌面、能绕过杯沿的脸；不用普通全身正站。',popularity:'本次页面为 7,580,965 Views。',boundary:'这不是严格意义的“无语”原作，改编时以求关注为主。'},
];

export const reactionReferences:ReactionReference[]=[...previousReactionReferences,...comedyReferences];

export const researchPrinciples=[
  {title:'先确定在回复什么',text:'回击、求哄、心虚、讨夸、无语各有自己的动词。可爱展示不自动等于好用的聊天表情。'},
  {title:'让接触产生后果',text:'拳头命中要回弹；食物要缺一口；被子会被抢回。摄影背景和道具要参与事件。'},
  {title:'一条剧情，一张首帧',text:'景别、重心、手势与动作路径按本条剧情设计。母版可共享，场景首帧不共享。'},
  {title:'快慢反差比一直快更清楚',text:'短蓄力、快速爆发、突然停住。部分参考只核验到画面，精确节拍仍需用实际成片测试。'},
];
