import { useState } from 'react';
import { ArrowDownToLine, Check, FileJson, Image, LoaderCircle, Package, RotateCcw, X } from 'lucide-react';
import type { Job, Project } from '../shared/types';
import { canResumeJob } from '../lib/jobs';
import { Modal, Status } from './Common';

export function ImagePreview({ job, project, onClose, onDownload }: { job: Job; project: Project; onClose: () => void; onDownload: (job: Job) => void }) {
  const [original, setOriginal] = useState(false);
  const [dark, setDark] = useState(false);
  return <Modal title={job.name} subtitle={`${job.provider} · ${job.model}`} onClose={onClose} wide><div className="image-preview-tools"><div className="segmented"><button className={!original ? 'active' : ''} onClick={() => setOriginal(false)}>当前成品</button><button className={original ? 'active' : ''} onClick={() => setOriginal(true)}>生成原图</button></div><button className="text-button" onClick={() => setDark(!dark)}>{dark ? '浅色背景' : '深色背景'}</button></div>{job.textMode === 'generated' && <p className="field-hint native-text-hint">文字已在生成原图里，两个视图都会保留。更改或移除文字需要重新生成，不会再叠加后期字幕。</p>}<div className={`image-preview-stage ${dark ? 'dark' : 'checker'}`}><img src={original || job.kind !== 'sticker' ? job.asset?.url : `/api/jobs/${job.id}/render?size=512&caption=1&v=${encodeURIComponent(project.updatedAt)}`} alt={job.name} /></div><div className="modal-actions"><span className="subtle">{job.asset?.width} × {job.asset?.height} · {job.asset?.hasAlpha ? '含 Alpha 通道，请检查边缘' : '实色背景，未伪装为透明'}</span><button className="button primary" onClick={() => onDownload(job)}><ArrowDownToLine size={16} />下载成品 PNG</button></div></Modal>;
}

export default function ResultsView({ project, jobs, onPreview, onDownload, onRetry, onResume, onCancel, onExport, onRecipe, busy, exportMode = false }: {
  project: Project; jobs: Job[]; onPreview: (job: Job) => void; onDownload: (job: Job) => void;
  onRetry: (job: Job) => void; onResume: (job: Job) => void; onCancel: (job: Job) => void; onExport: (captions: boolean, size: number) => void;
  onRecipe: () => void; busy: boolean; exportMode?: boolean;
}) {
  const [filter, setFilter] = useState('all');
  const [captions, setCaptions] = useState(true);
  const [size, setSize] = useState(512);
  const ownJobs = jobs.filter(j => j.projectId === project.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const completed = ownJobs.filter(j => j.kind === 'sticker' && j.status === 'succeeded' && j.asset);
  const unique = new Set(completed.map(j => j.reactionId)).size;
  const hasEmbedded = completed.some(job => job.textMode === 'generated');
  const working = ownJobs.filter(j => ['queued', 'running'].includes(j.status)).length;
  const shown = ownJobs.filter(j => filter === 'all' || (filter === 'succeeded' ? j.status === 'succeeded' : filter === 'active' ? ['queued', 'running'].includes(j.status) : ['failed', 'unknown'].includes(j.status)));
  return <div className="results-view"><div className="section-heading"><div><span className="eyebrow">{exportMode ? '05 / READY TO SAY HELLO' : '04 / FROM IDEAS TO STICKERS'}</span><h1>{exportMode ? <>带着可爱，<em>去聊天吧。</em></> : <>可爱正在，<em>一点点发生。</em></>}</h1><p>{exportMode ? '原图、加字成品与项目配方，打包带走。' : '每一张都独立生成，保留历史版本，随时回来挑选。'}</p></div><span className="section-doodle"><Package size={45} strokeWidth={1.2} /></span></div>
    <section className="export-banner"><div className="export-count"><strong>{String(unique).padStart(2, '0')}</strong><div><span>张表情已就绪</span><small>{working > 0 ? `${working} 张仍在排队或生成` : `${project.character.name} 的小小情绪收藏`}</small></div></div><div className="export-options"><label className="check-label"><input type="checkbox" checked={captions} onChange={e => setCaptions(e.target.checked)} />附上排字成品</label><select aria-label="导出尺寸" value={size} onChange={e => setSize(Number(e.target.value))}><option value={256}>256 px</option><option value={512}>512 px</option><option value={1024}>1024 px</option></select><button className="button primary" disabled={busy || unique === 0} onClick={() => onExport(captions, size)}>{busy ? <LoaderCircle size={16} className="spin" /> : <Package size={16} />}下载整套 ZIP</button></div></section>
    {hasEmbedded && <p className="field-hint native-text-hint export-text-hint">这一套包含随图生成的文字。取消「附上排字成品」只关闭后期排字，原图中的文字仍会保留。</p>}
    {exportMode && <div className="export-explain"><div><Image size={20} /><h3>原始 PNG + 排字成品</h3><p>保留最新成功版本，并按每张的文字设置导出；原图可能已带字，透明情况以实际图片为准。</p></div><div><Check size={20} /><h3>成套预览联系表</h3><p>一眼检查表演、线条和角色特征是否统一。</p></div><div><FileJson size={20} /><h3>可再次导入的配方</h3><p>角色、表情人格、动作与文字设置随包保存，不含密钥。</p><button className="text-button" onClick={onRecipe}>单独下载配方 →</button></div></div>}
    <div className="result-filters"><div className="segmented">{[{ id: 'all', name: '全部记录' }, { id: 'succeeded', name: '已完成' }, { id: 'active', name: '进行中' }, { id: 'failed', name: '需要关注' }].map(item => <button key={item.id} className={filter === item.id ? 'active' : ''} onClick={() => setFilter(item.id)}>{item.name}</button>)}</div><span className="subtle">{shown.length} 条记录</span></div>
    {shown.length === 0 ? <div className="empty-state"><div className="empty-stamp"><Image size={38} strokeWidth={1.3} /></div><h2>{filter === 'all' ? '第一张可爱，还在等待你。' : '这里暂时没有记录'}</h2><p>{filter === 'all' ? '选择角色参考图，在表情工坊里点「先做样张」开始。' : '生成任务的状态会自动更新。'}</p></div> : <div className="results-grid">{shown.map(job => <article className={`result-card ${job.status}`} key={job.id}><button className={`result-image ${job.asset ? 'checker' : ''}`} disabled={!job.asset} onClick={() => onPreview(job)}>{job.asset ? <img src={job.asset.url} alt={job.name} /> : <div className="result-placeholder">{['queued', 'running'].includes(job.status) ? <LoaderCircle size={34} className={job.status === 'running' ? 'spin' : ''} /> : <Image size={34} strokeWidth={1.3} />}<Status status={job.status} /></div>}</button><div className="result-body"><div className="result-title"><h3>{job.name}</h3><Status status={job.status} /></div><p>{job.kind === 'anchor' ? 'Q 版母版' : job.kind === 'character' ? '角色参考图' : '单张表情'} · {new Date(job.createdAt).toLocaleString('zh-CN', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>{job.error && <p className="job-error">{job.error}</p>}{job.remoteTaskId && <p className="remote-task-id">RunningHub 任务 <code>{job.remoteTaskId}</code></p>}{job.status === 'unknown' && <p className="field-hint">{canResumeJob(job) ? '原任务 ID 已保存，可以继续查询，无需重新提交绘图。' : '服务状态不确定，重试可能产生新的费用，请先核对服务商记录。'}</p>}<div className="result-actions">{job.asset && <button className="button small quiet" onClick={() => onDownload(job)}><ArrowDownToLine size={14} />PNG</button>}{['queued', 'running'].includes(job.status) ? <button className="button small quiet" disabled={busy} onClick={() => onCancel(job)}><X size={14} />取消</button> : canResumeJob(job) ? <button className="button small quiet" disabled={busy} onClick={() => onResume(job)}><RotateCcw size={14} />继续查询原任务</button> : job.status !== 'succeeded' && <button className="button small quiet" disabled={busy} onClick={() => onRetry(job)}><RotateCcw size={14} />重试</button>}<span title={`${job.provider} / ${job.model}`}>{job.provider}</span></div></div></article>)}</div>}
  </div>;
}
